// ==============================================================================
// Reaktar - Reactive Actor Framework for AUTOSAR Adaptive
// Part of the Pyarx project: https://github.com/pyarxlab/reaktar
//
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Pyarx Lab
//
// Generated Actor: CockpitDomainActor
// Source ARXML component: CockpitDomainApp
// DO NOT EDIT DIRECTLY - GENERATED BY reaktar scripts/generate_actor.py
// ==============================================================================

#pragma once

#include "hmi/hmiservice_skeleton.h"
#include "vehicle_supervisor/vehiclesupervisor_skeleton.h"
#include "body_control/bodycontrol_proxy.h"
#include "infotainment/geo/navigation/navigation_proxy.h"
#include "powertrain/powertrain_proxy.h"
#include "reaktar/tags.hpp"
#include "reaktar/traits.hpp"
#include "reaktar/proxy_slot.hpp"
#include "reaktar/actor_base.hpp"
#include "reaktar/port.hpp"
#include "reaktar/execution_policy.hpp"
#include <string>
#include <utility>
#include <optional>
#include <chrono>
#include <type_traits>
#include <atomic>
#include <mutex>

namespace reaktar {
namespace generated {

/**
 * @brief Non-templated Actor Base for CockpitDomain
 *
 * Provides pure ergonomic Tag aliases and unqualified `emit(...)`.
 * Does NOT inherit from Skeletons to completely eliminate name collisions/shadowing!
 */
class CockpitDomainActorBase
{
public:
    // ------------------------------------------------------------------------
    // Ergonomic Tag Aliases (brought directly into Actor class scope)
    // ------------------------------------------------------------------------
    using CabinSensors = ::reaktar::tags::powertrain::events::CabinSensors;
    using CalibrateOdometer = ::reaktar::tags::vehicle_supervisor::methods::CalibrateOdometer;
    using CalibrationKey = ::reaktar::tags::vehicle_supervisor::fields::CalibrationKey;
    using CurrentDriveMode = ::reaktar::tags::vehicle_supervisor::fields::CurrentDriveMode;
    using CurrentLocation = ::reaktar::tags::infotainment::geo::navigation::events::CurrentLocation;
    using EmergencyAlert = ::reaktar::tags::vehicle_supervisor::events::EmergencyAlert;
    using FlashLights = ::reaktar::tags::body_control::methods::FlashLights;
    using HardwareRevision = ::reaktar::tags::vehicle_supervisor::fields::HardwareRevision;
    using LockDoors = ::reaktar::tags::body_control::methods::LockDoors;
    using OutsideAirQuality = ::reaktar::tags::body_control::fields::OutsideAirQuality;
    using RainSensorLevel = ::reaktar::tags::body_control::fields::RainSensorLevel;
    using ResetTripMeter = ::reaktar::tags::vehicle_supervisor::methods::ResetTripMeter;
    using SetDestination = ::reaktar::tags::infotainment::geo::navigation::methods::SetDestination;
    using SetSpeedLimiter = ::reaktar::tags::vehicle_supervisor::methods::SetSpeedLimiter;
    using ShowPopup = ::reaktar::tags::hmi::methods::ShowPopup;
    using StatusNotification = ::reaktar::tags::hmi::events::StatusNotification;
    using TargetCabinTemperature = ::reaktar::tags::body_control::fields::TargetCabinTemperature;
    using TriggerDiagnostic = ::reaktar::tags::vehicle_supervisor::methods::TriggerDiagnostic;
    using VehicleSpeed = ::reaktar::tags::powertrain::events::VehicleSpeed;
    using WindowPosition = ::reaktar::tags::body_control::fields::WindowPosition;

    // ------------------------------------------------------------------------
    // Generated AUTOSAR Port Tags
    // ------------------------------------------------------------------------
    struct ports {
        struct HmiPort : public ::reaktar::ProvidedPortTag {
            static constexpr std::string_view name = "HmiPort";
            using port_tag = HmiPort;
            using kind_type = ::reaktar::ProvidedPortTag;
        };
        struct SupervisorPort : public ::reaktar::ProvidedPortTag {
            static constexpr std::string_view name = "SupervisorPort";
            using port_tag = SupervisorPort;
            using kind_type = ::reaktar::ProvidedPortTag;
        };
        struct BodyControlIn : public ::reaktar::RequiredPortTag {
            static constexpr std::string_view name = "BodyControlIn";
            using port_tag = BodyControlIn;
            using kind_type = ::reaktar::RequiredPortTag;
        };
        struct NavigationIn : public ::reaktar::RequiredPortTag {
            static constexpr std::string_view name = "NavigationIn";
            using port_tag = NavigationIn;
            using kind_type = ::reaktar::RequiredPortTag;
        };
        struct PowertrainIn : public ::reaktar::RequiredPortTag {
            static constexpr std::string_view name = "PowertrainIn";
            using port_tag = PowertrainIn;
            using kind_type = ::reaktar::RequiredPortTag;
        };

        // --------------------------------------------------------------------
        // Ergonomic Port Aliases (affixes stripped when collision-free)
        // --------------------------------------------------------------------
        using BodyControl = BodyControlIn;
        using Hmi = HmiPort;
        using Navigation = NavigationIn;
        using Powertrain = PowertrainIn;
        using Supervisor = SupervisorPort;
    };

    CockpitDomainActorBase() = default;
    virtual ~CockpitDomainActorBase() = default;

    body_control::proxy::BodyControlProxy* get_body_control_proxy() const noexcept { return body_control_slot_.get(); }
    bool is_body_control_ready() const noexcept { 
        return body_control_open_.load(std::memory_order_acquire) && body_control_slot_.is_available(); 
    }
    reaktar::ProxyLease<body_control::proxy::BodyControlProxy> acquire_body_control_proxy() { return body_control_slot_.acquire("body_control"); }
    std::optional<typename body_control::proxy::BodyControlProxy::HandleType> get_body_control_handle() const noexcept { 
        return body_control_slot_.get_handle(); 
    }
    infotainment::geo::navigation::proxy::NavigationProxy* get_navigation_proxy() const noexcept { return navigation_slot_.get(); }
    bool is_navigation_ready() const noexcept { 
        return navigation_open_.load(std::memory_order_acquire) && navigation_slot_.is_available(); 
    }
    reaktar::ProxyLease<infotainment::geo::navigation::proxy::NavigationProxy> acquire_navigation_proxy() { return navigation_slot_.acquire("navigation"); }
    std::optional<typename infotainment::geo::navigation::proxy::NavigationProxy::HandleType> get_navigation_handle() const noexcept { 
        return navigation_slot_.get_handle(); 
    }
    powertrain::proxy::PowertrainProxy* get_powertrain_proxy() const noexcept { return powertrain_slot_.get(); }
    bool is_powertrain_ready() const noexcept { 
        return powertrain_open_.load(std::memory_order_acquire) && powertrain_slot_.is_available(); 
    }
    reaktar::ProxyLease<powertrain::proxy::PowertrainProxy> acquire_powertrain_proxy() { return powertrain_slot_.acquire("powertrain"); }
    std::optional<typename powertrain::proxy::PowertrainProxy::HandleType> get_powertrain_handle() const noexcept { 
        return powertrain_slot_.get_handle(); 
    }

    static constexpr size_t kConsumedProxyCount = 3;

    /**
     * @brief Check whether all required service proxies have been resolved and published.
     * Always returns true if this Actor consumes 0 services.
     */
    bool is_ready() const noexcept {
        return readiness_.is_ready([this] {
            return (body_control_slot_.is_available() && navigation_slot_.is_available() && powertrain_slot_.is_available());
        });
    }

    /**
     * @brief Block until all required service proxies have been resolved and published.
     * Fully zero-cost: if this Actor consumes 0 services, returns true immediately without locks or cv.
     */
    bool wait_until_ready() {
        return readiness_.wait_until_ready([this] {
            return (body_control_slot_.is_available() && navigation_slot_.is_available() && powertrain_slot_.is_available());
        });
    }

    /**
     * @brief Block with a timeout until all required service proxies have been resolved and published.
     * Returns true if ready, false if timeout expired.
     */
    template <typename Rep, typename Period>
    bool wait_until_ready(const std::chrono::duration<Rep, Period>& timeout) {
        return readiness_.wait_until_ready([this] {
            return (body_control_slot_.is_available() && navigation_slot_.is_available() && powertrain_slot_.is_available());
        }, timeout);
    }

protected:
    void notify_proxy_resolved() {
        readiness_.notify_resolved();
    }

    reaktar::ReadinessTracker<kConsumedProxyCount> readiness_{};
    reaktar::ProxySlot<body_control::proxy::BodyControlProxy> body_control_slot_{};
    mutable std::mutex body_control_port_mutex_{};
    std::optional<ara::com::FindServiceHandle> body_control_find_handle_{std::nullopt};
    std::atomic<bool> body_control_open_{false};
    uint64_t body_control_generation_{0};
    reaktar::ProxySlot<infotainment::geo::navigation::proxy::NavigationProxy> navigation_slot_{};
    mutable std::mutex navigation_port_mutex_{};
    std::optional<ara::com::FindServiceHandle> navigation_find_handle_{std::nullopt};
    std::atomic<bool> navigation_open_{false};
    uint64_t navigation_generation_{0};
    reaktar::ProxySlot<powertrain::proxy::PowertrainProxy> powertrain_slot_{};
    mutable std::mutex powertrain_port_mutex_{};
    std::optional<ara::com::FindServiceHandle> powertrain_find_handle_{std::nullopt};
    std::atomic<bool> powertrain_open_{false};
    uint64_t powertrain_generation_{0};
};
/**
 * @brief Code-generated CRTP Actor for CockpitDomain
 */
template <typename Derived, typename ExecutionPolicy = ::reaktar::DirectExecution>
class CockpitDomainActor : public CockpitDomainActorBase {
public:
    using Base = CockpitDomainActorBase;
    using execution_policy_type = ExecutionPolicy;
    using Base::get_body_control_proxy;
    using Base::get_navigation_proxy;
    using Base::get_powertrain_proxy;

    ExecutionPolicy& execution_policy() noexcept { return execution_policy_; }
    const ExecutionPolicy& execution_policy() const noexcept { return execution_policy_; }

    template <typename Fn>
    auto sync(Fn&& fn) {
        if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
            return std::forward<Fn>(fn);
        } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
            return [this, f = std::forward<Fn>(fn)](auto&&... args) mutable {
                std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                return f(std::forward<decltype(args)>(args)...);
            };
        } else {
            return [this, f = std::forward<Fn>(fn)](auto&&... args) mutable {
                return this->execution_policy_.execute([&] {
                    return f(std::forward<decltype(args)>(args)...);
                });
            };
        }
    }

protected:
    ExecutionPolicy execution_policy_{};

public:

    // Skeleton Adapter for HmiServiceInterface
    class HmiPortSkeletonAdapter : public hmi::skeleton::HmiServiceSkeleton {
        CockpitDomainActor* actor_;
    public:
        explicit HmiPortSkeletonAdapter(
            CockpitDomainActor* a,
            reaktar::InstanceSpecifier instance_spec,
            ara::com::MethodCallProcessingMode mode
        )
            : hmi::skeleton::HmiServiceSkeleton(std::move(instance_spec), mode), actor_(a) {}

        // Skeleton RPC Method Overrides
        using ShowPopupRetType = decltype(std::declval<hmi::skeleton::HmiServiceSkeleton&>().ShowPopup(std::declval<const ara::core::String&>(), std::declval<const uint32_t&>()));

        ShowPopupRetType ShowPopup(const ara::core::String& message, const uint32_t& priority) override {
            using MethodTag = ::reaktar::tags::hmi::methods::ShowPopup;
            if constexpr (has_method_handler_v<Derived, MethodTag, const ara::core::String&, const uint32_t&> ||
                          has_method_handler_v<Derived, MethodTag, ara::core::String, uint32_t>) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, message, priority))>) {
                        actor_->self().on(MethodTag{}, message, priority);
                        return result_adapter<ShowPopupRetType, void>::adapt();
                    } else {
                        return result_adapter<ShowPopupRetType, decltype(actor_->self().on(MethodTag{}, message, priority))>::adapt(
                            actor_->self().on(MethodTag{}, message, priority)
                        );
                    }
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(actor_->execution_policy_.mutex());
                    if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, message, priority))>) {
                        actor_->self().on(MethodTag{}, message, priority);
                        return result_adapter<ShowPopupRetType, void>::adapt();
                    } else {
                        return result_adapter<ShowPopupRetType, decltype(actor_->self().on(MethodTag{}, message, priority))>::adapt(
                            actor_->self().on(MethodTag{}, message, priority)
                        );
                    }
                } else {
                    return actor_->execution_policy_.execute([&]() -> ShowPopupRetType {
                        if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, message, priority))>) {
                            actor_->self().on(MethodTag{}, message, priority);
                            return result_adapter<ShowPopupRetType, void>::adapt();
                        } else {
                            return result_adapter<ShowPopupRetType, decltype(actor_->self().on(MethodTag{}, message, priority))>::adapt(
                                actor_->self().on(MethodTag{}, message, priority)
                            );
                        }
                    });
                }
            }
            else if constexpr (has_direct_method_handler_v<Derived, const ara::core::String&, const uint32_t&> ||
                               has_direct_method_handler_v<Derived, ara::core::String, uint32_t>) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    if constexpr (std::is_void_v<decltype(actor_->self().on(message, priority))>) {
                        actor_->self().on(message, priority);
                        return result_adapter<ShowPopupRetType, void>::adapt();
                    } else {
                        return result_adapter<ShowPopupRetType, decltype(actor_->self().on(message, priority))>::adapt(
                            actor_->self().on(message, priority)
                        );
                    }
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(actor_->execution_policy_.mutex());
                    if constexpr (std::is_void_v<decltype(actor_->self().on(message, priority))>) {
                        actor_->self().on(message, priority);
                        return result_adapter<ShowPopupRetType, void>::adapt();
                    } else {
                        return result_adapter<ShowPopupRetType, decltype(actor_->self().on(message, priority))>::adapt(
                            actor_->self().on(message, priority)
                        );
                    }
                } else {
                    return actor_->execution_policy_.execute([&]() -> ShowPopupRetType {
                        if constexpr (std::is_void_v<decltype(actor_->self().on(message, priority))>) {
                            actor_->self().on(message, priority);
                            return result_adapter<ShowPopupRetType, void>::adapt();
                        } else {
                            return result_adapter<ShowPopupRetType, decltype(actor_->self().on(message, priority))>::adapt(
                                actor_->self().on(message, priority)
                            );
                        }
                    });
                }
            }
            else {
                return result_adapter<ShowPopupRetType, void>::adapt();
            }
        }
    };

    HmiPortSkeletonAdapter hmiport_skeleton_;
    std::atomic<bool> hmiport_offered_{false};
    mutable std::mutex hmiport_port_mutex_{};

    hmi::skeleton::HmiServiceSkeleton& get_hmiport_skeleton() { return hmiport_skeleton_; }

    // Skeleton Adapter for VehicleSupervisorInterface
    class SupervisorPortSkeletonAdapter : public vehicle_supervisor::skeleton::VehicleSupervisorSkeleton {
        CockpitDomainActor* actor_;
    public:
        explicit SupervisorPortSkeletonAdapter(
            CockpitDomainActor* a,
            reaktar::InstanceSpecifier instance_spec,
            ara::com::MethodCallProcessingMode mode
        )
            : vehicle_supervisor::skeleton::VehicleSupervisorSkeleton(std::move(instance_spec), mode), actor_(a) {}

        // Skeleton RPC Method Overrides
        using CalibrateOdometerRetType = decltype(std::declval<vehicle_supervisor::skeleton::VehicleSupervisorSkeleton&>().CalibrateOdometer(std::declval<const uint32_t&>()));

        CalibrateOdometerRetType CalibrateOdometer(const uint32_t& current_km) override {
            using MethodTag = ::reaktar::tags::vehicle_supervisor::methods::CalibrateOdometer;
            if constexpr (has_method_handler_v<Derived, MethodTag, const uint32_t&> ||
                          has_method_handler_v<Derived, MethodTag, uint32_t>) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, current_km))>) {
                        actor_->self().on(MethodTag{}, current_km);
                        return result_adapter<CalibrateOdometerRetType, void>::adapt();
                    } else {
                        return result_adapter<CalibrateOdometerRetType, decltype(actor_->self().on(MethodTag{}, current_km))>::adapt(
                            actor_->self().on(MethodTag{}, current_km)
                        );
                    }
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(actor_->execution_policy_.mutex());
                    if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, current_km))>) {
                        actor_->self().on(MethodTag{}, current_km);
                        return result_adapter<CalibrateOdometerRetType, void>::adapt();
                    } else {
                        return result_adapter<CalibrateOdometerRetType, decltype(actor_->self().on(MethodTag{}, current_km))>::adapt(
                            actor_->self().on(MethodTag{}, current_km)
                        );
                    }
                } else {
                    return actor_->execution_policy_.execute([&]() -> CalibrateOdometerRetType {
                        if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, current_km))>) {
                            actor_->self().on(MethodTag{}, current_km);
                            return result_adapter<CalibrateOdometerRetType, void>::adapt();
                        } else {
                            return result_adapter<CalibrateOdometerRetType, decltype(actor_->self().on(MethodTag{}, current_km))>::adapt(
                                actor_->self().on(MethodTag{}, current_km)
                            );
                        }
                    });
                }
            }
            else if constexpr (has_direct_method_handler_v<Derived, const uint32_t&> ||
                               has_direct_method_handler_v<Derived, uint32_t>) {
                static_assert(!sizeof(Derived*), "reaktar::on() collision: RPC method argument signature is shared across multiple methods. You must specify the method tag: on(MethodTag, ...).");
            }
            else {
                return result_adapter<CalibrateOdometerRetType, void>::adapt();
            }
        }
        void ResetTripMeter() override {
            using MethodTag = ::reaktar::tags::vehicle_supervisor::methods::ResetTripMeter;
            if constexpr (has_method_handler_v<Derived, MethodTag> ||
                          has_method_handler_v<Derived, MethodTag>) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    actor_->self().on(MethodTag{});
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(actor_->execution_policy_.mutex());
                    actor_->self().on(MethodTag{});
                } else {
                    actor_->execution_policy_.execute([&] {
                        actor_->self().on(MethodTag{});
                    });
                }
            }
            else if constexpr (has_direct_method_handler_v<Derived> ||
                               has_direct_method_handler_v<Derived>) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    actor_->self().on();
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(actor_->execution_policy_.mutex());
                    actor_->self().on();
                } else {
                    actor_->execution_policy_.execute([&] {
                        actor_->self().on();
                    });
                }
            }
            else {
                // Unhandled fire-and-forget method
            }
        }
        using SetSpeedLimiterRetType = decltype(std::declval<vehicle_supervisor::skeleton::VehicleSupervisorSkeleton&>().SetSpeedLimiter(std::declval<const float&>(), std::declval<const bool&>()));

        SetSpeedLimiterRetType SetSpeedLimiter(const float& max_kmh, const bool& active) override {
            using MethodTag = ::reaktar::tags::vehicle_supervisor::methods::SetSpeedLimiter;
            if constexpr (has_method_handler_v<Derived, MethodTag, const float&, const bool&> ||
                          has_method_handler_v<Derived, MethodTag, float, bool>) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, max_kmh, active))>) {
                        actor_->self().on(MethodTag{}, max_kmh, active);
                        return result_adapter<SetSpeedLimiterRetType, void>::adapt();
                    } else {
                        return result_adapter<SetSpeedLimiterRetType, decltype(actor_->self().on(MethodTag{}, max_kmh, active))>::adapt(
                            actor_->self().on(MethodTag{}, max_kmh, active)
                        );
                    }
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(actor_->execution_policy_.mutex());
                    if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, max_kmh, active))>) {
                        actor_->self().on(MethodTag{}, max_kmh, active);
                        return result_adapter<SetSpeedLimiterRetType, void>::adapt();
                    } else {
                        return result_adapter<SetSpeedLimiterRetType, decltype(actor_->self().on(MethodTag{}, max_kmh, active))>::adapt(
                            actor_->self().on(MethodTag{}, max_kmh, active)
                        );
                    }
                } else {
                    return actor_->execution_policy_.execute([&]() -> SetSpeedLimiterRetType {
                        if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, max_kmh, active))>) {
                            actor_->self().on(MethodTag{}, max_kmh, active);
                            return result_adapter<SetSpeedLimiterRetType, void>::adapt();
                        } else {
                            return result_adapter<SetSpeedLimiterRetType, decltype(actor_->self().on(MethodTag{}, max_kmh, active))>::adapt(
                                actor_->self().on(MethodTag{}, max_kmh, active)
                            );
                        }
                    });
                }
            }
            else if constexpr (has_direct_method_handler_v<Derived, const float&, const bool&> ||
                               has_direct_method_handler_v<Derived, float, bool>) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    if constexpr (std::is_void_v<decltype(actor_->self().on(max_kmh, active))>) {
                        actor_->self().on(max_kmh, active);
                        return result_adapter<SetSpeedLimiterRetType, void>::adapt();
                    } else {
                        return result_adapter<SetSpeedLimiterRetType, decltype(actor_->self().on(max_kmh, active))>::adapt(
                            actor_->self().on(max_kmh, active)
                        );
                    }
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(actor_->execution_policy_.mutex());
                    if constexpr (std::is_void_v<decltype(actor_->self().on(max_kmh, active))>) {
                        actor_->self().on(max_kmh, active);
                        return result_adapter<SetSpeedLimiterRetType, void>::adapt();
                    } else {
                        return result_adapter<SetSpeedLimiterRetType, decltype(actor_->self().on(max_kmh, active))>::adapt(
                            actor_->self().on(max_kmh, active)
                        );
                    }
                } else {
                    return actor_->execution_policy_.execute([&]() -> SetSpeedLimiterRetType {
                        if constexpr (std::is_void_v<decltype(actor_->self().on(max_kmh, active))>) {
                            actor_->self().on(max_kmh, active);
                            return result_adapter<SetSpeedLimiterRetType, void>::adapt();
                        } else {
                            return result_adapter<SetSpeedLimiterRetType, decltype(actor_->self().on(max_kmh, active))>::adapt(
                                actor_->self().on(max_kmh, active)
                            );
                        }
                    });
                }
            }
            else {
                return result_adapter<SetSpeedLimiterRetType, void>::adapt();
            }
        }
        using TriggerDiagnosticRetType = decltype(std::declval<vehicle_supervisor::skeleton::VehicleSupervisorSkeleton&>().TriggerDiagnostic(std::declval<const uint32_t&>()));

        TriggerDiagnosticRetType TriggerDiagnostic(const uint32_t& code) override {
            using MethodTag = ::reaktar::tags::vehicle_supervisor::methods::TriggerDiagnostic;
            if constexpr (has_method_handler_v<Derived, MethodTag, const uint32_t&> ||
                          has_method_handler_v<Derived, MethodTag, uint32_t>) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, code))>) {
                        actor_->self().on(MethodTag{}, code);
                        return result_adapter<TriggerDiagnosticRetType, void>::adapt();
                    } else {
                        return result_adapter<TriggerDiagnosticRetType, decltype(actor_->self().on(MethodTag{}, code))>::adapt(
                            actor_->self().on(MethodTag{}, code)
                        );
                    }
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(actor_->execution_policy_.mutex());
                    if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, code))>) {
                        actor_->self().on(MethodTag{}, code);
                        return result_adapter<TriggerDiagnosticRetType, void>::adapt();
                    } else {
                        return result_adapter<TriggerDiagnosticRetType, decltype(actor_->self().on(MethodTag{}, code))>::adapt(
                            actor_->self().on(MethodTag{}, code)
                        );
                    }
                } else {
                    return actor_->execution_policy_.execute([&]() -> TriggerDiagnosticRetType {
                        if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, code))>) {
                            actor_->self().on(MethodTag{}, code);
                            return result_adapter<TriggerDiagnosticRetType, void>::adapt();
                        } else {
                            return result_adapter<TriggerDiagnosticRetType, decltype(actor_->self().on(MethodTag{}, code))>::adapt(
                                actor_->self().on(MethodTag{}, code)
                            );
                        }
                    });
                }
            }
            else if constexpr (has_direct_method_handler_v<Derived, const uint32_t&> ||
                               has_direct_method_handler_v<Derived, uint32_t>) {
                static_assert(!sizeof(Derived*), "reaktar::on() collision: RPC method argument signature is shared across multiple methods. You must specify the method tag: on(MethodTag, ...).");
            }
            else {
                return result_adapter<TriggerDiagnosticRetType, void>::adapt();
            }
        }
    };

    SupervisorPortSkeletonAdapter supervisorport_skeleton_;
    std::atomic<bool> supervisorport_offered_{false};
    mutable std::mutex supervisorport_port_mutex_{};

    vehicle_supervisor::skeleton::VehicleSupervisorSkeleton& get_supervisorport_skeleton() { return supervisorport_skeleton_; }

    using legal_signatures = std::tuple<
        reaktar::sig<>,
        reaktar::sig<::reaktar::tags::vehicle_supervisor::methods::ResetTripMeter>,
        reaktar::sig<float>,
        reaktar::sig<uint32_t>,
        reaktar::sig<vehicle_data::CabinSensorData>,
        reaktar::sig<vehicle_data::DriveMode>,
        reaktar::sig<vehicle_data::LocationPoint>,
        reaktar::sig<vehicle_data::SpeedData>,
        reaktar::sig<::reaktar::tags::body_control::fields::OutsideAirQuality, uint32_t>,
        reaktar::sig<::reaktar::tags::body_control::fields::RainSensorLevel, uint32_t>,
        reaktar::sig<::reaktar::tags::body_control::fields::TargetCabinTemperature, float>,
        reaktar::sig<::reaktar::tags::body_control::fields::WindowPosition, uint32_t>,
        reaktar::sig<::reaktar::tags::infotainment::geo::navigation::events::CurrentLocation, vehicle_data::LocationPoint>,
        reaktar::sig<::reaktar::tags::powertrain::events::CabinSensors, vehicle_data::CabinSensorData>,
        reaktar::sig<::reaktar::tags::powertrain::events::VehicleSpeed, vehicle_data::SpeedData>,
        reaktar::sig<::reaktar::tags::vehicle_supervisor::fields::CalibrationKey, uint32_t>,
        reaktar::sig<::reaktar::tags::vehicle_supervisor::fields::CurrentDriveMode, vehicle_data::DriveMode>,
        reaktar::sig<::reaktar::tags::vehicle_supervisor::methods::CalibrateOdometer, uint32_t>,
        reaktar::sig<::reaktar::tags::vehicle_supervisor::methods::TriggerDiagnostic, uint32_t>,
        reaktar::sig<ara::core::String, uint32_t>,
        reaktar::sig<float, bool>,
        reaktar::sig<::reaktar::tags::hmi::methods::ShowPopup, ara::core::String, uint32_t>,
        reaktar::sig<::reaktar::tags::vehicle_supervisor::methods::SetSpeedLimiter, float, bool>
    >;

    explicit CockpitDomainActor(
        reaktar::InstanceSpecifier hmiport_instance = reaktar::InstanceSpecifier("CockpitDomain/RootSwComponent/HmiPort"),
        reaktar::InstanceSpecifier supervisorport_instance = reaktar::InstanceSpecifier("CockpitDomain/RootSwComponent/SupervisorPort"),
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent
    )
        : CockpitDomainActorBase()
        , hmiport_skeleton_(this, std::move(hmiport_instance), mode)
        , supervisorport_skeleton_(this, std::move(supervisorport_instance), mode)
    {
        if constexpr (::reaktar::strict_validation_enabled) {
            using LegalSignaturesTuple = legal_signatures;

            static_assert(!reaktar::has_rogue_handler_v<Derived, LegalSignaturesTuple
                , ara::core::String
                , bool
                , float
                , uint32_t
                , vehicle_data::CabinSensorData
                , vehicle_data::DriveMode
                , vehicle_data::LocationPoint
                , vehicle_data::SpeedData
                , ::reaktar::tags::body_control::fields::OutsideAirQuality
                , ::reaktar::tags::body_control::fields::RainSensorLevel
                , ::reaktar::tags::body_control::fields::TargetCabinTemperature
                , ::reaktar::tags::body_control::fields::WindowPosition
                , ::reaktar::tags::hmi::methods::ShowPopup
                , ::reaktar::tags::infotainment::geo::navigation::events::CurrentLocation
                , ::reaktar::tags::powertrain::events::CabinSensors
                , ::reaktar::tags::powertrain::events::VehicleSpeed
                , ::reaktar::tags::vehicle_supervisor::fields::CalibrationKey
                , ::reaktar::tags::vehicle_supervisor::fields::CurrentDriveMode
                , ::reaktar::tags::vehicle_supervisor::methods::CalibrateOdometer
                , ::reaktar::tags::vehicle_supervisor::methods::ResetTripMeter
                , ::reaktar::tags::vehicle_supervisor::methods::SetSpeedLimiter
                , ::reaktar::tags::vehicle_supervisor::methods::TriggerDiagnostic
            >,
            "\n"
            "====================================================================================\n"
            " Reaktar Compile Error: Rogue/orphan on(...) handler detected in CockpitDomain!\n"
            " You declared an on(...) method taking a parameter type or signature combination that\n"
            " does NOT exist in this ARXML interface (or is a typo/dead handler).\n"
            " To disable strict ARXML compile-time validation, build without -DREAKTAR_STRICT_VALIDATION\n"
            "====================================================================================\n"
            );
        }
    }

    virtual ~CockpitDomainActor() = default;

    Derived& self() { return static_cast<Derived&>(*this); }
    // ------------------------------------------------------------------------
    // OUTBOUND: emit<Tag>(args...) OR untagged emit(val)
    // ------------------------------------------------------------------------
    template <typename Tag, typename... Args>
    auto emit(Args&&... args) {
        if constexpr (std::is_same_v<Tag, hmi::events::StatusNotification>) {
            hmiport_skeleton_.StatusNotification.Send(std::forward<Args>(args)...);
            return ::reaktar::EmitStatus{true};
        }
        else if constexpr (std::is_same_v<Tag, vehicle_supervisor::events::EmergencyAlert>) {
            supervisorport_skeleton_.EmergencyAlert.Send(std::forward<Args>(args)...);
            return ::reaktar::EmitStatus{true};
        }
        else if constexpr (std::is_same_v<Tag, ::reaktar::tags::body_control::methods::FlashLights>) {
            auto proxy_lease = this->body_control_slot_.acquire("body_control");
            if (proxy_lease) {
                proxy_lease->FlashLights(std::forward<Args>(args)...);
                return ::reaktar::EmitStatus{true};
            }
            return ::reaktar::EmitStatus{false};
        }
        else if constexpr (std::is_same_v<Tag, ::reaktar::tags::body_control::methods::LockDoors>) {
            auto proxy_lease = this->body_control_slot_.acquire("body_control");
            using AsyncResType = decltype(make_async_result(proxy_lease->LockDoors(std::forward<Args>(args)...)));
            if (proxy_lease) {
                return make_async_result(proxy_lease->LockDoors(std::forward<Args>(args)...));
            }
            return AsyncResType::Failed();
        }
        else if constexpr (std::is_same_v<Tag, body_control::fields::TargetCabinTemperature>) {
            auto proxy_lease = this->body_control_slot_.acquire("body_control");
            using AsyncResType = decltype(make_async_result(proxy_lease->TargetCabinTemperature.Set(std::forward<Args>(args)...)));
            if (proxy_lease) {
                return make_async_result(proxy_lease->TargetCabinTemperature.Set(std::forward<Args>(args)...));
            }
            return AsyncResType::Failed();
        }
        else if constexpr (std::is_same_v<Tag, body_control::fields::WindowPosition>) {
            auto proxy_lease = this->body_control_slot_.acquire("body_control");
            using AsyncResType = decltype(make_async_result(proxy_lease->WindowPosition.Set(std::forward<Args>(args)...)));
            if (proxy_lease) {
                return make_async_result(proxy_lease->WindowPosition.Set(std::forward<Args>(args)...));
            }
            return AsyncResType::Failed();
        }
        else if constexpr (std::is_same_v<Tag, ::reaktar::tags::infotainment::geo::navigation::methods::SetDestination>) {
            auto proxy_lease = this->navigation_slot_.acquire("navigation");
            using AsyncResType = decltype(make_async_result(proxy_lease->SetDestination(std::forward<Args>(args)...)));
            if (proxy_lease) {
                return make_async_result(proxy_lease->SetDestination(std::forward<Args>(args)...));
            }
            return AsyncResType::Failed();
        }
        else {
            static_assert(!sizeof(Tag*), "reaktar: emit called with unknown tag!");
        }
    }

    template <typename Tag, typename... Args>
    auto call(Args&&... args) {
        return emit<Tag>(std::forward<Args>(args)...);
    }

    template <typename... Args>
    auto emit(Args&&... args) {
        if constexpr (sizeof...(Args) == 1) {
            using PayloadType = std::decay_t<typename std::tuple_element<0, std::tuple<Args...>>::type>;
            if constexpr (std::is_same_v<PayloadType, ara::core::String>) {
                hmiport_skeleton_.StatusNotification.Send(std::forward<Args>(args)...);
                return ::reaktar::EmitStatus{true};
            }
            else if constexpr (std::is_same_v<PayloadType, vehicle_data::EmergencyAlert>) {
                supervisorport_skeleton_.EmergencyAlert.Send(std::forward<Args>(args)...);
                return ::reaktar::EmitStatus{true};
            }
            else if constexpr (std::is_same_v<PayloadType, bool>) {
                auto proxy_lease = this->body_control_slot_.acquire("body_control");
                using AsyncResType = decltype(make_async_result(proxy_lease->LockDoors(std::forward<Args>(args)...)));
                if (proxy_lease) {
                    return make_async_result(proxy_lease->LockDoors(std::forward<Args>(args)...));
                }
                return AsyncResType::Failed();
            }
            else {
                static_assert(!sizeof...(Args), "reaktar: emit(payload) failed! The payload type is not produced by any skeleton event, field, or single-arg RPC method in this Actor.");
            }
        }
        else {
            using SigTuple = std::tuple<std::decay_t<Args>...>;
            if constexpr (std::is_same_v<SigTuple, std::tuple<uint32_t, uint32_t>>) {
                auto proxy_lease = this->body_control_slot_.acquire("body_control");
                if (proxy_lease) {
                    proxy_lease->FlashLights(std::forward<Args>(args)...);
                    return ::reaktar::EmitStatus{true};
                }
                return ::reaktar::EmitStatus{false};
            }
            else if constexpr (std::is_same_v<SigTuple, std::tuple<float, float, uint32_t>>) {
                auto proxy_lease = this->navigation_slot_.acquire("navigation");
                using AsyncResType = decltype(make_async_result(proxy_lease->SetDestination(std::forward<Args>(args)...)));
                if (proxy_lease) {
                    return make_async_result(proxy_lease->SetDestination(std::forward<Args>(args)...));
                }
                return AsyncResType::Failed();
            }
            else {
                static_assert(!sizeof...(Args), "reaktar: emit(args...) failed! The argument list does not match any unique proxy RPC method in this Actor. Use emit<Tag>(args...) if ambiguous.");
            }
        }
    }
    // ------------------------------------------------------------------------
    // Granular Port Lifecycle Controls
    // ------------------------------------------------------------------------

    /**
     * @brief Open (activate) an individual AUTOSAR Port in a thread-safe manner.
     * For a Provided Port (P-Port / Skeleton): Calls OfferService.
     * For a Required Port (R-Port / Proxy): Calls StartFindService with ZERO locks held.
     */
    template <typename PortTag>
    void open_port() {
        static_assert(::reaktar::is_port_v<PortTag>, "open_port requires a valid generated Port Tag (e.g. ports::MyPort)!");
        if constexpr (std::is_same_v<PortTag, typename Base::ports::HmiPort>) {
            open_hmiport_provided_port();
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::SupervisorPort>) {
            open_supervisorport_provided_port();
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::BodyControlIn>) {
            open_body_control_required_port();
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::NavigationIn>) {
            open_navigation_required_port();
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::PowertrainIn>) {
            open_powertrain_required_port();
        }
    }

    /**
     * @brief Close (deactivate) an individual AUTOSAR Port in a thread-safe manner.
     * For a Provided Port (P-Port / Skeleton): Calls StopOfferService.
     * For a Required Port (R-Port / Proxy): Calls StopFindService with ZERO locks held, unsubscribes, and resets slot.
     */
    template <typename PortTag>
    void close_port() {
        static_assert(::reaktar::is_port_v<PortTag>, "close_port requires a valid generated Port Tag (e.g. ports::MyPort)!");
        if constexpr (std::is_same_v<PortTag, typename Base::ports::HmiPort>) {
            close_hmiport_provided_port();
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::SupervisorPort>) {
            close_supervisorport_provided_port();
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::BodyControlIn>) {
            close_body_control_required_port();
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::NavigationIn>) {
            close_navigation_required_port();
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::PowertrainIn>) {
            close_powertrain_required_port();
        }
    }

    /**
     * @brief Check whether an individual AUTOSAR Port is ready (wait-free and lock-free).
     * For a Provided Port (P-Port / Skeleton): Returns true if currently offered.
     * For a Required Port (R-Port / Proxy): Returns true if proxy is acquired and available.
     */
    template <typename PortTag>
    bool is_ready() const noexcept {
        static_assert(::reaktar::is_port_v<PortTag>, "is_ready requires a valid generated Port Tag (e.g. ports::MyPort)!");
        if constexpr (std::is_same_v<PortTag, typename Base::ports::HmiPort>) {
            return this->hmiport_offered_.load(std::memory_order_acquire);
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::SupervisorPort>) {
            return this->supervisorport_offered_.load(std::memory_order_acquire);
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::BodyControlIn>) {
            return this->body_control_open_.load(std::memory_order_acquire) && this->body_control_slot_.is_available();
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::NavigationIn>) {
            return this->navigation_open_.load(std::memory_order_acquire) && this->navigation_slot_.is_available();
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::PowertrainIn>) {
            return this->powertrain_open_.load(std::memory_order_acquire) && this->powertrain_slot_.is_available();
        }
    }

    /**
     * @brief Check whether an individual AUTOSAR Port has been requested open.
     */
    template <typename PortTag>
    bool is_port_open() const noexcept {
        static_assert(::reaktar::is_port_v<PortTag>, "is_port_open requires a valid generated Port Tag (e.g. ports::MyPort)!");
        if constexpr (std::is_same_v<PortTag, typename Base::ports::HmiPort>) {
            return this->hmiport_offered_.load(std::memory_order_acquire);
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::SupervisorPort>) {
            return this->supervisorport_offered_.load(std::memory_order_acquire);
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::BodyControlIn>) {
            return this->body_control_open_.load(std::memory_order_acquire);
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::NavigationIn>) {
            return this->navigation_open_.load(std::memory_order_acquire);
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::PowertrainIn>) {
            return this->powertrain_open_.load(std::memory_order_acquire);
        }
    }

    /**
     * @brief Generational ticket query for diagnostics and invariant testing.
     */
    template <typename PortTag>
    uint64_t get_port_generation() const noexcept {
        static_assert(::reaktar::is_port_v<PortTag>, "get_port_generation requires a valid generated Port Tag!");
        if constexpr (std::is_same_v<PortTag, typename Base::ports::HmiPort>) {
            return 0;
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::SupervisorPort>) {
            return 0;
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::BodyControlIn>) {
            std::lock_guard<std::mutex> lock(this->body_control_port_mutex_);
            return this->body_control_generation_;
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::NavigationIn>) {
            std::lock_guard<std::mutex> lock(this->navigation_port_mutex_);
            return this->navigation_generation_;
        }
        else if constexpr (std::is_same_v<PortTag, typename Base::ports::PowertrainIn>) {
            std::lock_guard<std::mutex> lock(this->powertrain_port_mutex_);
            return this->powertrain_generation_;
        }
    }

    // Bring ActorBase::is_ready() (no-arg readiness check across all ports) into scope
    using Base::is_ready;
    using Base::wait_until_ready;

    // ------------------------------------------------------------------------
    // Process-Wide Lifecycle Controls (Granular Defaults)
    // ------------------------------------------------------------------------

    void start() {
        this->template open_port<typename Base::ports::HmiPort>();
        this->template open_port<typename Base::ports::SupervisorPort>();
        this->template open_port<typename Base::ports::BodyControlIn>();
        this->template open_port<typename Base::ports::NavigationIn>();
        this->template open_port<typename Base::ports::PowertrainIn>();
    }

    void stop() {
        this->template close_port<typename Base::ports::HmiPort>();
        this->template close_port<typename Base::ports::SupervisorPort>();
        this->template close_port<typename Base::ports::BodyControlIn>();
        this->template close_port<typename Base::ports::NavigationIn>();
        this->template close_port<typename Base::ports::PowertrainIn>();
    }

private:
    void open_hmiport_provided_port() {
        std::lock_guard<std::mutex> lock(this->hmiport_port_mutex_);
        if (!this->hmiport_offered_.load(std::memory_order_relaxed)) {
            bind_skeleton_fields();
            this->hmiport_skeleton_.OfferService();
            this->hmiport_offered_.store(true, std::memory_order_release);
        }
    }
    void open_supervisorport_provided_port() {
        std::lock_guard<std::mutex> lock(this->supervisorport_port_mutex_);
        if (!this->supervisorport_offered_.load(std::memory_order_relaxed)) {
            bind_skeleton_fields();
            this->supervisorport_skeleton_.OfferService();
            this->supervisorport_offered_.store(true, std::memory_order_release);
        }
    }
    void open_body_control_required_port() {
        uint64_t my_gen{0};
        {
            std::lock_guard<std::mutex> lock(this->body_control_port_mutex_);
            if (this->body_control_open_.load(std::memory_order_acquire)) {
                return; // Already open or opening
            }
            this->body_control_open_.store(true, std::memory_order_release);
            my_gen = ++this->body_control_generation_;
        }

        bool find_started = false;
        struct ExceptionRollbackGuard {
            std::atomic<bool>& open_flag;
            bool& ok;
            ~ExceptionRollbackGuard() {
                if (!ok) {
                    open_flag.store(false, std::memory_order_release);
                }
            }
        } rollback_guard{this->body_control_open_, find_started};

        // Call StartFindService with ZERO locks held
        auto find_res = body_control::proxy::BodyControlProxy::StartFindService(
            [this, my_gen](ara::com::ServiceHandleContainer<typename body_control::proxy::BodyControlProxy::HandleType> handles, ara::com::FindServiceHandle) {
                if (!this->body_control_open_.load(std::memory_order_acquire)) {
                    return; // Port was closed
                }
                {
                    std::lock_guard<std::mutex> h_lock(this->body_control_port_mutex_);
                    if (this->body_control_generation_ != my_gen) {
                        return; // Stale callback from an earlier generation
                    }
                }
                if (handles.empty()) {
                    std::lock_guard<std::mutex> h_lock(this->body_control_port_mutex_);
                    if (!this->body_control_open_.load(std::memory_order_acquire) ||
                        this->body_control_generation_ != my_gen) {
                        return; // Closed or generation shifted concurrently
                    }
                    this->body_control_slot_.reset();
                } else {
                    if (auto cur_h = this->body_control_slot_.get_handle(); cur_h.has_value() && *cur_h == handles[0]) {
                        return; // Same handle, already active
                    }
                    // Zero-downtime update: do NOT wipe slot before creating new proxy!
                    // ProxySlot::publish handles atomic cell exchange, bounded reader drain, and teardown hook cleanly.
                    auto new_proxy = std::make_unique<body_control::proxy::BodyControlProxy>(handles[0]);
                    bind_body_control_events(new_proxy.get());
                    bind_body_control_fields(new_proxy.get());

                    auto teardown_hook = []([[maybe_unused]] body_control::proxy::BodyControlProxy& p) {
                        p.OutsideAirQuality.Unsubscribe();
                        p.RainSensorLevel.Unsubscribe();
                        p.TargetCabinTemperature.Unsubscribe();
                        p.WindowPosition.Unsubscribe();
                    };

                    {
                        std::lock_guard<std::mutex> h_lock(this->body_control_port_mutex_);
                        if (!this->body_control_open_.load(std::memory_order_acquire) ||
                            this->body_control_generation_ != my_gen) {
                            return; // Closed or generation shifted concurrently
                        }
                        this->body_control_slot_.publish(std::move(new_proxy), handles[0], teardown_hook);
                    }
                    this->notify_proxy_resolved();
                }
            },
            reaktar::InstanceSpecifier("CockpitDomain/RootSwComponent/BodyControlIn")
        );

        std::optional<ara::com::FindServiceHandle> handle;
        if constexpr (reaktar::is_result_v<decltype(find_res)>) {
            if (find_res.HasValue()) {
                handle = find_res.Value();
            }
        } else {
            handle = find_res;
        }

        if (!handle.has_value()) {
            std::lock_guard<std::mutex> lock(this->body_control_port_mutex_);
            if (this->body_control_generation_ == my_gen) {
                this->body_control_open_.store(false, std::memory_order_release);
            }
            return;
        }

        find_started = true; // Successfully started, prevent rollback

        std::unique_lock<std::mutex> lock(this->body_control_port_mutex_);
        if (!this->body_control_open_.load(std::memory_order_acquire) || this->body_control_generation_ != my_gen) {
            // Port was closed or generation shifted while StartFindService was executing!
            lock.unlock();
            body_control::proxy::BodyControlProxy::StopFindService(*handle);
            return;
        }
        this->body_control_find_handle_ = *handle;
    }
    void open_navigation_required_port() {
        uint64_t my_gen{0};
        {
            std::lock_guard<std::mutex> lock(this->navigation_port_mutex_);
            if (this->navigation_open_.load(std::memory_order_acquire)) {
                return; // Already open or opening
            }
            this->navigation_open_.store(true, std::memory_order_release);
            my_gen = ++this->navigation_generation_;
        }

        bool find_started = false;
        struct ExceptionRollbackGuard {
            std::atomic<bool>& open_flag;
            bool& ok;
            ~ExceptionRollbackGuard() {
                if (!ok) {
                    open_flag.store(false, std::memory_order_release);
                }
            }
        } rollback_guard{this->navigation_open_, find_started};

        // Call StartFindService with ZERO locks held
        auto find_res = infotainment::geo::navigation::proxy::NavigationProxy::StartFindService(
            [this, my_gen](ara::com::ServiceHandleContainer<typename infotainment::geo::navigation::proxy::NavigationProxy::HandleType> handles, ara::com::FindServiceHandle) {
                if (!this->navigation_open_.load(std::memory_order_acquire)) {
                    return; // Port was closed
                }
                {
                    std::lock_guard<std::mutex> h_lock(this->navigation_port_mutex_);
                    if (this->navigation_generation_ != my_gen) {
                        return; // Stale callback from an earlier generation
                    }
                }
                if (handles.empty()) {
                    std::lock_guard<std::mutex> h_lock(this->navigation_port_mutex_);
                    if (!this->navigation_open_.load(std::memory_order_acquire) ||
                        this->navigation_generation_ != my_gen) {
                        return; // Closed or generation shifted concurrently
                    }
                    this->navigation_slot_.reset();
                } else {
                    if (auto cur_h = this->navigation_slot_.get_handle(); cur_h.has_value() && *cur_h == handles[0]) {
                        return; // Same handle, already active
                    }
                    // Zero-downtime update: do NOT wipe slot before creating new proxy!
                    // ProxySlot::publish handles atomic cell exchange, bounded reader drain, and teardown hook cleanly.
                    auto new_proxy = std::make_unique<infotainment::geo::navigation::proxy::NavigationProxy>(handles[0]);
                    bind_navigation_events(new_proxy.get());
                    bind_navigation_fields(new_proxy.get());

                    auto teardown_hook = []([[maybe_unused]] infotainment::geo::navigation::proxy::NavigationProxy& p) {
                        p.CurrentLocation.Unsubscribe();
                    };

                    {
                        std::lock_guard<std::mutex> h_lock(this->navigation_port_mutex_);
                        if (!this->navigation_open_.load(std::memory_order_acquire) ||
                            this->navigation_generation_ != my_gen) {
                            return; // Closed or generation shifted concurrently
                        }
                        this->navigation_slot_.publish(std::move(new_proxy), handles[0], teardown_hook);
                    }
                    this->notify_proxy_resolved();
                }
            },
            reaktar::InstanceSpecifier("CockpitDomain/RootSwComponent/NavigationIn")
        );

        std::optional<ara::com::FindServiceHandle> handle;
        if constexpr (reaktar::is_result_v<decltype(find_res)>) {
            if (find_res.HasValue()) {
                handle = find_res.Value();
            }
        } else {
            handle = find_res;
        }

        if (!handle.has_value()) {
            std::lock_guard<std::mutex> lock(this->navigation_port_mutex_);
            if (this->navigation_generation_ == my_gen) {
                this->navigation_open_.store(false, std::memory_order_release);
            }
            return;
        }

        find_started = true; // Successfully started, prevent rollback

        std::unique_lock<std::mutex> lock(this->navigation_port_mutex_);
        if (!this->navigation_open_.load(std::memory_order_acquire) || this->navigation_generation_ != my_gen) {
            // Port was closed or generation shifted while StartFindService was executing!
            lock.unlock();
            infotainment::geo::navigation::proxy::NavigationProxy::StopFindService(*handle);
            return;
        }
        this->navigation_find_handle_ = *handle;
    }
    void open_powertrain_required_port() {
        uint64_t my_gen{0};
        {
            std::lock_guard<std::mutex> lock(this->powertrain_port_mutex_);
            if (this->powertrain_open_.load(std::memory_order_acquire)) {
                return; // Already open or opening
            }
            this->powertrain_open_.store(true, std::memory_order_release);
            my_gen = ++this->powertrain_generation_;
        }

        bool find_started = false;
        struct ExceptionRollbackGuard {
            std::atomic<bool>& open_flag;
            bool& ok;
            ~ExceptionRollbackGuard() {
                if (!ok) {
                    open_flag.store(false, std::memory_order_release);
                }
            }
        } rollback_guard{this->powertrain_open_, find_started};

        // Call StartFindService with ZERO locks held
        auto find_res = powertrain::proxy::PowertrainProxy::StartFindService(
            [this, my_gen](ara::com::ServiceHandleContainer<typename powertrain::proxy::PowertrainProxy::HandleType> handles, ara::com::FindServiceHandle) {
                if (!this->powertrain_open_.load(std::memory_order_acquire)) {
                    return; // Port was closed
                }
                {
                    std::lock_guard<std::mutex> h_lock(this->powertrain_port_mutex_);
                    if (this->powertrain_generation_ != my_gen) {
                        return; // Stale callback from an earlier generation
                    }
                }
                if (handles.empty()) {
                    std::lock_guard<std::mutex> h_lock(this->powertrain_port_mutex_);
                    if (!this->powertrain_open_.load(std::memory_order_acquire) ||
                        this->powertrain_generation_ != my_gen) {
                        return; // Closed or generation shifted concurrently
                    }
                    this->powertrain_slot_.reset();
                } else {
                    if (auto cur_h = this->powertrain_slot_.get_handle(); cur_h.has_value() && *cur_h == handles[0]) {
                        return; // Same handle, already active
                    }
                    // Zero-downtime update: do NOT wipe slot before creating new proxy!
                    // ProxySlot::publish handles atomic cell exchange, bounded reader drain, and teardown hook cleanly.
                    auto new_proxy = std::make_unique<powertrain::proxy::PowertrainProxy>(handles[0]);
                    bind_powertrain_events(new_proxy.get());
                    bind_powertrain_fields(new_proxy.get());

                    auto teardown_hook = []([[maybe_unused]] powertrain::proxy::PowertrainProxy& p) {
                        p.CabinSensors.Unsubscribe();
                        p.VehicleSpeed.Unsubscribe();
                    };

                    {
                        std::lock_guard<std::mutex> h_lock(this->powertrain_port_mutex_);
                        if (!this->powertrain_open_.load(std::memory_order_acquire) ||
                            this->powertrain_generation_ != my_gen) {
                            return; // Closed or generation shifted concurrently
                        }
                        this->powertrain_slot_.publish(std::move(new_proxy), handles[0], teardown_hook);
                    }
                    this->notify_proxy_resolved();
                }
            },
            reaktar::InstanceSpecifier("CockpitDomain/RootSwComponent/PowertrainIn")
        );

        std::optional<ara::com::FindServiceHandle> handle;
        if constexpr (reaktar::is_result_v<decltype(find_res)>) {
            if (find_res.HasValue()) {
                handle = find_res.Value();
            }
        } else {
            handle = find_res;
        }

        if (!handle.has_value()) {
            std::lock_guard<std::mutex> lock(this->powertrain_port_mutex_);
            if (this->powertrain_generation_ == my_gen) {
                this->powertrain_open_.store(false, std::memory_order_release);
            }
            return;
        }

        find_started = true; // Successfully started, prevent rollback

        std::unique_lock<std::mutex> lock(this->powertrain_port_mutex_);
        if (!this->powertrain_open_.load(std::memory_order_acquire) || this->powertrain_generation_ != my_gen) {
            // Port was closed or generation shifted while StartFindService was executing!
            lock.unlock();
            powertrain::proxy::PowertrainProxy::StopFindService(*handle);
            return;
        }
        this->powertrain_find_handle_ = *handle;
    }

    void close_hmiport_provided_port() {
        std::lock_guard<std::mutex> lock(this->hmiport_port_mutex_);
        if (this->hmiport_offered_.load(std::memory_order_relaxed)) {
            this->hmiport_skeleton_.StopOfferService();
            this->hmiport_offered_.store(false, std::memory_order_release);
        }
    }
    void close_supervisorport_provided_port() {
        std::lock_guard<std::mutex> lock(this->supervisorport_port_mutex_);
        if (this->supervisorport_offered_.load(std::memory_order_relaxed)) {
            this->supervisorport_skeleton_.StopOfferService();
            this->supervisorport_offered_.store(false, std::memory_order_release);
        }
    }
    void close_body_control_required_port() {
        std::optional<ara::com::FindServiceHandle> handle_to_stop;
        {
            std::lock_guard<std::mutex> lock(this->body_control_port_mutex_);
            if (!this->body_control_open_.load(std::memory_order_relaxed) && !this->body_control_find_handle_.has_value()) {
                return;
            }
            this->body_control_open_.store(false, std::memory_order_release);
            ++this->body_control_generation_;
            handle_to_stop = this->body_control_find_handle_;
            this->body_control_find_handle_.reset();
            this->body_control_slot_.reset();
        }

        if (handle_to_stop.has_value()) {
            body_control::proxy::BodyControlProxy::StopFindService(*handle_to_stop);
        }
    }
    void close_navigation_required_port() {
        std::optional<ara::com::FindServiceHandle> handle_to_stop;
        {
            std::lock_guard<std::mutex> lock(this->navigation_port_mutex_);
            if (!this->navigation_open_.load(std::memory_order_relaxed) && !this->navigation_find_handle_.has_value()) {
                return;
            }
            this->navigation_open_.store(false, std::memory_order_release);
            ++this->navigation_generation_;
            handle_to_stop = this->navigation_find_handle_;
            this->navigation_find_handle_.reset();
            this->navigation_slot_.reset();
        }

        if (handle_to_stop.has_value()) {
            infotainment::geo::navigation::proxy::NavigationProxy::StopFindService(*handle_to_stop);
        }
    }
    void close_powertrain_required_port() {
        std::optional<ara::com::FindServiceHandle> handle_to_stop;
        {
            std::lock_guard<std::mutex> lock(this->powertrain_port_mutex_);
            if (!this->powertrain_open_.load(std::memory_order_relaxed) && !this->powertrain_find_handle_.has_value()) {
                return;
            }
            this->powertrain_open_.store(false, std::memory_order_release);
            ++this->powertrain_generation_;
            handle_to_stop = this->powertrain_find_handle_;
            this->powertrain_find_handle_.reset();
            this->powertrain_slot_.reset();
        }

        if (handle_to_stop.has_value()) {
            powertrain::proxy::PowertrainProxy::StopFindService(*handle_to_stop);
        }
    }

private:

    void bind_skeleton_fields() {
        if constexpr (has_on_field_set_v<Derived, vehicle_supervisor::fields::CalibrationKey, uint32_t>) {
            supervisorport_skeleton_.CalibrationKey.RegisterSetHandler([this](const uint32_t& val) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    return result_adapter<reaktar::Future<uint32_t>, decltype(self().on_set(vehicle_supervisor::fields::CalibrationKey{}, val))>::adapt(
                        self().on_set(vehicle_supervisor::fields::CalibrationKey{}, val)
                    );
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                    return result_adapter<reaktar::Future<uint32_t>, decltype(self().on_set(vehicle_supervisor::fields::CalibrationKey{}, val))>::adapt(
                        self().on_set(vehicle_supervisor::fields::CalibrationKey{}, val)
                    );
                } else {
                    return this->execution_policy_.execute([&] {
                        return result_adapter<reaktar::Future<uint32_t>, decltype(self().on_set(vehicle_supervisor::fields::CalibrationKey{}, val))>::adapt(
                            self().on_set(vehicle_supervisor::fields::CalibrationKey{}, val)
                        );
                    });
                }
            });
        }
        else if constexpr (has_on_direct_field_set_v<Derived, uint32_t>) {
            supervisorport_skeleton_.CalibrationKey.RegisterSetHandler([this](const uint32_t& val) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    return result_adapter<reaktar::Future<uint32_t>, decltype(self().on_set(val))>::adapt(
                        self().on_set(val)
                    );
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                    return result_adapter<reaktar::Future<uint32_t>, decltype(self().on_set(val))>::adapt(
                        self().on_set(val)
                    );
                } else {
                    return this->execution_policy_.execute([&] {
                        return result_adapter<reaktar::Future<uint32_t>, decltype(self().on_set(val))>::adapt(
                            self().on_set(val)
                        );
                    });
                }
            });
        }
        // Initialise field value before OfferService (required by AUTOSAR Adaptive caching/notifier semantics)
        supervisorport_skeleton_.CurrentDriveMode.Update({});
        if constexpr (has_on_field_set_v<Derived, vehicle_supervisor::fields::CurrentDriveMode, vehicle_data::DriveMode>) {
            supervisorport_skeleton_.CurrentDriveMode.RegisterSetHandler([this](const vehicle_data::DriveMode& val) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    return result_adapter<reaktar::Future<vehicle_data::DriveMode>, decltype(self().on_set(vehicle_supervisor::fields::CurrentDriveMode{}, val))>::adapt(
                        self().on_set(vehicle_supervisor::fields::CurrentDriveMode{}, val)
                    );
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                    return result_adapter<reaktar::Future<vehicle_data::DriveMode>, decltype(self().on_set(vehicle_supervisor::fields::CurrentDriveMode{}, val))>::adapt(
                        self().on_set(vehicle_supervisor::fields::CurrentDriveMode{}, val)
                    );
                } else {
                    return this->execution_policy_.execute([&] {
                        return result_adapter<reaktar::Future<vehicle_data::DriveMode>, decltype(self().on_set(vehicle_supervisor::fields::CurrentDriveMode{}, val))>::adapt(
                            self().on_set(vehicle_supervisor::fields::CurrentDriveMode{}, val)
                        );
                    });
                }
            });
        }
        else if constexpr (has_on_direct_field_set_v<Derived, vehicle_data::DriveMode>) {
            supervisorport_skeleton_.CurrentDriveMode.RegisterSetHandler([this](const vehicle_data::DriveMode& val) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    return result_adapter<reaktar::Future<vehicle_data::DriveMode>, decltype(self().on_set(val))>::adapt(
                        self().on_set(val)
                    );
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                    return result_adapter<reaktar::Future<vehicle_data::DriveMode>, decltype(self().on_set(val))>::adapt(
                        self().on_set(val)
                    );
                } else {
                    return this->execution_policy_.execute([&] {
                        return result_adapter<reaktar::Future<vehicle_data::DriveMode>, decltype(self().on_set(val))>::adapt(
                            self().on_set(val)
                        );
                    });
                }
            });
        }
        // Initialise field value before OfferService (required by AUTOSAR Adaptive caching/notifier semantics)
        supervisorport_skeleton_.HardwareRevision.Update({});
    }

    void bind_body_control_events(body_control::proxy::BodyControlProxy* proxy) {
        if (!proxy) return;
    }

    void bind_body_control_fields(body_control::proxy::BodyControlProxy* proxy) {
        if (!proxy) return;
        // Field Notifier: OutsideAirQuality (uint32_t)
        if constexpr (has_on_event_v<Derived, body_control::fields::OutsideAirQuality, uint32_t>) {
            proxy->OutsideAirQuality.SetReceiveHandler([this]() {
                auto lease = this->body_control_slot_.try_acquire();
                if (lease) {
                    lease->OutsideAirQuality.GetNewSamples([this](auto&& s) {
                        if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                            self().on(body_control::fields::OutsideAirQuality{}, *s);
                        } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                            std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                            self().on(body_control::fields::OutsideAirQuality{}, *s);
                        } else {
                            this->execution_policy_.execute([&] {
                                self().on(body_control::fields::OutsideAirQuality{}, *s);
                            });
                        }
                    });
                }
            });
            proxy->OutsideAirQuality.Subscribe(10);
        }
        else if constexpr (has_on_direct_event_v<Derived, uint32_t>) {
            static_assert(!sizeof(Derived*), "reaktar::on() collision: type 'uint32_t' is shared across multiple incoming channels (events/fields). You must specify the tag: void on(body_control::fields::OutsideAirQuality, const uint32_t& val).");
        }
        // Field Notifier: RainSensorLevel (uint32_t)
        if constexpr (has_on_event_v<Derived, body_control::fields::RainSensorLevel, uint32_t>) {
            proxy->RainSensorLevel.SetReceiveHandler([this]() {
                auto lease = this->body_control_slot_.try_acquire();
                if (lease) {
                    lease->RainSensorLevel.GetNewSamples([this](auto&& s) {
                        if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                            self().on(body_control::fields::RainSensorLevel{}, *s);
                        } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                            std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                            self().on(body_control::fields::RainSensorLevel{}, *s);
                        } else {
                            this->execution_policy_.execute([&] {
                                self().on(body_control::fields::RainSensorLevel{}, *s);
                            });
                        }
                    });
                }
            });
            proxy->RainSensorLevel.Subscribe(10);
        }
        else if constexpr (has_on_direct_event_v<Derived, uint32_t>) {
            static_assert(!sizeof(Derived*), "reaktar::on() collision: type 'uint32_t' is shared across multiple incoming channels (events/fields). You must specify the tag: void on(body_control::fields::RainSensorLevel, const uint32_t& val).");
        }
        // Field Notifier: TargetCabinTemperature (float)
        if constexpr (has_on_event_v<Derived, body_control::fields::TargetCabinTemperature, float>) {
            proxy->TargetCabinTemperature.SetReceiveHandler([this]() {
                auto lease = this->body_control_slot_.try_acquire();
                if (lease) {
                    lease->TargetCabinTemperature.GetNewSamples([this](auto&& s) {
                        if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                            self().on(body_control::fields::TargetCabinTemperature{}, *s);
                        } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                            std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                            self().on(body_control::fields::TargetCabinTemperature{}, *s);
                        } else {
                            this->execution_policy_.execute([&] {
                                self().on(body_control::fields::TargetCabinTemperature{}, *s);
                            });
                        }
                    });
                }
            });
            proxy->TargetCabinTemperature.Subscribe(10);
        }
        else if constexpr (has_on_direct_event_v<Derived, float>) {
            proxy->TargetCabinTemperature.SetReceiveHandler([this]() {
                auto lease = this->body_control_slot_.try_acquire();
                if (lease) {
                    lease->TargetCabinTemperature.GetNewSamples([this](auto&& s) {
                        if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                            self().on(*s);
                        } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                            std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                            self().on(*s);
                        } else {
                            this->execution_policy_.execute([&] {
                                self().on(*s);
                            });
                        }
                    });
                }
            });
            proxy->TargetCabinTemperature.Subscribe(10);
        }
        // Field Notifier: WindowPosition (uint32_t)
        if constexpr (has_on_event_v<Derived, body_control::fields::WindowPosition, uint32_t>) {
            proxy->WindowPosition.SetReceiveHandler([this]() {
                auto lease = this->body_control_slot_.try_acquire();
                if (lease) {
                    lease->WindowPosition.GetNewSamples([this](auto&& s) {
                        if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                            self().on(body_control::fields::WindowPosition{}, *s);
                        } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                            std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                            self().on(body_control::fields::WindowPosition{}, *s);
                        } else {
                            this->execution_policy_.execute([&] {
                                self().on(body_control::fields::WindowPosition{}, *s);
                            });
                        }
                    });
                }
            });
            proxy->WindowPosition.Subscribe(10);
        }
        else if constexpr (has_on_direct_event_v<Derived, uint32_t>) {
            static_assert(!sizeof(Derived*), "reaktar::on() collision: type 'uint32_t' is shared across multiple incoming channels (events/fields). You must specify the tag: void on(body_control::fields::WindowPosition, const uint32_t& val).");
        }
    }
    void bind_navigation_events(infotainment::geo::navigation::proxy::NavigationProxy* proxy) {
        if (!proxy) return;
        // Event: CurrentLocation (vehicle_data::LocationPoint)
        if constexpr (has_on_event_v<Derived, infotainment::geo::navigation::events::CurrentLocation, vehicle_data::LocationPoint>) {
            proxy->CurrentLocation.SetReceiveHandler([this]() {
                auto lease = this->navigation_slot_.try_acquire();
                if (lease) {
                    lease->CurrentLocation.GetNewSamples([this](auto&& s) {
                        if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                            self().on(infotainment::geo::navigation::events::CurrentLocation{}, *s);
                        } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                            std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                            self().on(infotainment::geo::navigation::events::CurrentLocation{}, *s);
                        } else {
                            this->execution_policy_.execute([&] {
                                self().on(infotainment::geo::navigation::events::CurrentLocation{}, *s);
                            });
                        }
                    });
                }
            });
            proxy->CurrentLocation.Subscribe(10);
        }
        else if constexpr (has_on_direct_event_v<Derived, vehicle_data::LocationPoint>) {
            proxy->CurrentLocation.SetReceiveHandler([this]() {
                auto lease = this->navigation_slot_.try_acquire();
                if (lease) {
                    lease->CurrentLocation.GetNewSamples([this](auto&& s) {
                        if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                            self().on(*s);
                        } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                            std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                            self().on(*s);
                        } else {
                            this->execution_policy_.execute([&] {
                                self().on(*s);
                            });
                        }
                    });
                }
            });
            proxy->CurrentLocation.Subscribe(10);
        }
    }

    void bind_navigation_fields(infotainment::geo::navigation::proxy::NavigationProxy* proxy) {
        if (!proxy) return;
    }
    void bind_powertrain_events(powertrain::proxy::PowertrainProxy* proxy) {
        if (!proxy) return;
        // Event: CabinSensors (vehicle_data::CabinSensorData)
        if constexpr (has_on_event_v<Derived, powertrain::events::CabinSensors, vehicle_data::CabinSensorData>) {
            proxy->CabinSensors.SetReceiveHandler([this]() {
                auto lease = this->powertrain_slot_.try_acquire();
                if (lease) {
                    lease->CabinSensors.GetNewSamples([this](auto&& s) {
                        if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                            self().on(powertrain::events::CabinSensors{}, *s);
                        } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                            std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                            self().on(powertrain::events::CabinSensors{}, *s);
                        } else {
                            this->execution_policy_.execute([&] {
                                self().on(powertrain::events::CabinSensors{}, *s);
                            });
                        }
                    });
                }
            });
            proxy->CabinSensors.Subscribe(10);
        }
        else if constexpr (has_on_direct_event_v<Derived, vehicle_data::CabinSensorData>) {
            proxy->CabinSensors.SetReceiveHandler([this]() {
                auto lease = this->powertrain_slot_.try_acquire();
                if (lease) {
                    lease->CabinSensors.GetNewSamples([this](auto&& s) {
                        if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                            self().on(*s);
                        } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                            std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                            self().on(*s);
                        } else {
                            this->execution_policy_.execute([&] {
                                self().on(*s);
                            });
                        }
                    });
                }
            });
            proxy->CabinSensors.Subscribe(10);
        }
        // Event: VehicleSpeed (vehicle_data::SpeedData)
        if constexpr (has_on_event_v<Derived, powertrain::events::VehicleSpeed, vehicle_data::SpeedData>) {
            proxy->VehicleSpeed.SetReceiveHandler([this]() {
                auto lease = this->powertrain_slot_.try_acquire();
                if (lease) {
                    lease->VehicleSpeed.GetNewSamples([this](auto&& s) {
                        if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                            self().on(powertrain::events::VehicleSpeed{}, *s);
                        } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                            std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                            self().on(powertrain::events::VehicleSpeed{}, *s);
                        } else {
                            this->execution_policy_.execute([&] {
                                self().on(powertrain::events::VehicleSpeed{}, *s);
                            });
                        }
                    });
                }
            });
            proxy->VehicleSpeed.Subscribe(10);
        }
        else if constexpr (has_on_direct_event_v<Derived, vehicle_data::SpeedData>) {
            proxy->VehicleSpeed.SetReceiveHandler([this]() {
                auto lease = this->powertrain_slot_.try_acquire();
                if (lease) {
                    lease->VehicleSpeed.GetNewSamples([this](auto&& s) {
                        if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                            self().on(*s);
                        } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                            std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                            self().on(*s);
                        } else {
                            this->execution_policy_.execute([&] {
                                self().on(*s);
                            });
                        }
                    });
                }
            });
            proxy->VehicleSpeed.Subscribe(10);
        }
    }

    void bind_powertrain_fields(powertrain::proxy::PowertrainProxy* proxy) {
        if (!proxy) return;
    }
};

// Convenience alias mapping Component name to Executable Actor
template <typename Derived, typename ExecutionPolicy = ::reaktar::DirectExecution>
using CockpitDomainAppActor = CockpitDomainActor<Derived, ExecutionPolicy>;
using CockpitDomainAppActorBase = CockpitDomainActorBase;

// Convenience aliases for specifying ExecutionPolicy first
template <typename Derived, typename ExecutionPolicy = ::reaktar::SynchronizedExecution>
using CockpitDomainActorWithPolicy = CockpitDomainActor<Derived, ExecutionPolicy>;

template <typename Derived, typename ExecutionPolicy = ::reaktar::SynchronizedExecution>
using CockpitDomainAppActorWithPolicy = CockpitDomainActor<Derived, ExecutionPolicy>;

} // namespace generated
} // namespace reaktar