// ==============================================================================
// Reaktar - Reactive Actor Framework for AUTOSAR Adaptive
// Part of the Pyarx project: https://github.com/pyarxlab/reaktar
//
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Pyarx Lab
//
// Generated Actor: TelemetryActor
// Source ARXML component: TelemetryApp
// DO NOT EDIT DIRECTLY - GENERATED BY reaktar scripts/generate_actor.py
// ==============================================================================

#pragma once

#include "vehicle_supervisor/vehiclesupervisor_skeleton.h"
#include "reaktar/tags.hpp"
#include "reaktar/traits.hpp"
#include "reaktar/proxy_slot.hpp"
#include "reaktar/actor_base.hpp"
#include "reaktar/execution_policy.hpp"
#include <string>
#include <utility>
#include <optional>
#include <chrono>
#include <type_traits>

namespace reaktar {
namespace generated {

/**
 * @brief Non-templated Actor Base for Telemetry
 *
 * Provides pure ergonomic Tag aliases and unqualified `emit(...)`.
 * Does NOT inherit from Skeletons to completely eliminate name collisions/shadowing!
 */
class TelemetryActorBase
{
public:
    // ------------------------------------------------------------------------
    // Ergonomic Tag Aliases (brought directly into Actor class scope)
    // ------------------------------------------------------------------------
    using CalibrateOdometer = ::reaktar::tags::vehicle_supervisor::methods::CalibrateOdometer;
    using CalibrationKey = ::reaktar::tags::vehicle_supervisor::fields::CalibrationKey;
    using CurrentDriveMode = ::reaktar::tags::vehicle_supervisor::fields::CurrentDriveMode;
    using EmergencyAlert = ::reaktar::tags::vehicle_supervisor::events::EmergencyAlert;
    using HardwareRevision = ::reaktar::tags::vehicle_supervisor::fields::HardwareRevision;
    using ResetTripMeter = ::reaktar::tags::vehicle_supervisor::methods::ResetTripMeter;
    using SetSpeedLimiter = ::reaktar::tags::vehicle_supervisor::methods::SetSpeedLimiter;
    using TriggerDiagnostic = ::reaktar::tags::vehicle_supervisor::methods::TriggerDiagnostic;

    TelemetryActorBase() = default;
    virtual ~TelemetryActorBase() = default;


    static constexpr size_t kConsumedProxyCount = 0;

    /**
     * @brief Check whether all required service proxies have been resolved and published.
     * Always returns true if this Actor consumes 0 services.
     */
    bool is_ready() const noexcept {
        return true;
    }

    /**
     * @brief Block until all required service proxies have been resolved and published.
     * Fully zero-cost: if this Actor consumes 0 services, returns true immediately without locks or cv.
     */
    bool wait_until_ready() {
        return true;
    }

    /**
     * @brief Block with a timeout until all required service proxies have been resolved and published.
     * Returns true if ready, false if timeout expired.
     */
    template <typename Rep, typename Period>
    bool wait_until_ready(const std::chrono::duration<Rep, Period>& timeout) {
        (void)timeout;
        return true;
    }

protected:
};
/**
 * @brief Code-generated CRTP Actor for Telemetry
 */
template <typename Derived, typename ExecutionPolicy = ::reaktar::DirectExecution>
class TelemetryActor : public TelemetryActorBase {
public:
    using Base = TelemetryActorBase;
    using execution_policy_type = ExecutionPolicy;

    ExecutionPolicy& execution_policy() noexcept { return execution_policy_; }
    const ExecutionPolicy& execution_policy() const noexcept { return execution_policy_; }

    template <typename Fn>
    auto sync(Fn&& fn) {
        if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
            return std::forward<Fn>(fn);
        } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
            return [this, f = std::forward<Fn>(fn)](auto&&... args) mutable {
                std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                return f(std::forward<decltype(args)>(args)...);
            };
        } else {
            return [this, f = std::forward<Fn>(fn)](auto&&... args) mutable {
                return this->execution_policy_.execute([&] {
                    return f(std::forward<decltype(args)>(args)...);
                });
            };
        }
    }

protected:
    ExecutionPolicy execution_policy_{};

public:

    // Skeleton Adapter for VehicleSupervisorInterface
    class SupervisorPortSkeletonAdapter : public vehicle_supervisor::skeleton::VehicleSupervisorSkeleton {
        TelemetryActor* actor_;
    public:
        explicit SupervisorPortSkeletonAdapter(
            TelemetryActor* a,
            reaktar::InstanceSpecifier instance_spec,
            ara::com::MethodCallProcessingMode mode
        )
            : vehicle_supervisor::skeleton::VehicleSupervisorSkeleton(std::move(instance_spec), mode), actor_(a) {}

        // Skeleton RPC Method Overrides
        using CalibrateOdometerRetType = decltype(std::declval<vehicle_supervisor::skeleton::VehicleSupervisorSkeleton&>().CalibrateOdometer(std::declval<const uint32_t&>()));

        CalibrateOdometerRetType CalibrateOdometer(const uint32_t& current_km) override {
            using MethodTag = ::reaktar::tags::vehicle_supervisor::methods::CalibrateOdometer;
            if constexpr (has_method_handler_v<Derived, MethodTag, const uint32_t&> ||
                          has_method_handler_v<Derived, MethodTag, uint32_t>) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, current_km))>) {
                        actor_->self().on(MethodTag{}, current_km);
                        return result_adapter<CalibrateOdometerRetType, void>::adapt();
                    } else {
                        return result_adapter<CalibrateOdometerRetType, decltype(actor_->self().on(MethodTag{}, current_km))>::adapt(
                            actor_->self().on(MethodTag{}, current_km)
                        );
                    }
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(actor_->execution_policy_.mutex());
                    if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, current_km))>) {
                        actor_->self().on(MethodTag{}, current_km);
                        return result_adapter<CalibrateOdometerRetType, void>::adapt();
                    } else {
                        return result_adapter<CalibrateOdometerRetType, decltype(actor_->self().on(MethodTag{}, current_km))>::adapt(
                            actor_->self().on(MethodTag{}, current_km)
                        );
                    }
                } else {
                    return actor_->execution_policy_.execute([&]() -> CalibrateOdometerRetType {
                        if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, current_km))>) {
                            actor_->self().on(MethodTag{}, current_km);
                            return result_adapter<CalibrateOdometerRetType, void>::adapt();
                        } else {
                            return result_adapter<CalibrateOdometerRetType, decltype(actor_->self().on(MethodTag{}, current_km))>::adapt(
                                actor_->self().on(MethodTag{}, current_km)
                            );
                        }
                    });
                }
            }
            else if constexpr (has_direct_method_handler_v<Derived, const uint32_t&> ||
                               has_direct_method_handler_v<Derived, uint32_t>) {
                static_assert(!sizeof(Derived*), "reaktar::on() collision: RPC method argument signature is shared across multiple methods. You must specify the method tag: on(MethodTag, ...).");
            }
            else {
                return result_adapter<CalibrateOdometerRetType, void>::adapt();
            }
        }
        void ResetTripMeter() override {
            using MethodTag = ::reaktar::tags::vehicle_supervisor::methods::ResetTripMeter;
            if constexpr (has_method_handler_v<Derived, MethodTag> ||
                          has_method_handler_v<Derived, MethodTag>) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    actor_->self().on(MethodTag{});
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(actor_->execution_policy_.mutex());
                    actor_->self().on(MethodTag{});
                } else {
                    actor_->execution_policy_.execute([&] {
                        actor_->self().on(MethodTag{});
                    });
                }
            }
            else if constexpr (has_direct_method_handler_v<Derived> ||
                               has_direct_method_handler_v<Derived>) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    actor_->self().on();
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(actor_->execution_policy_.mutex());
                    actor_->self().on();
                } else {
                    actor_->execution_policy_.execute([&] {
                        actor_->self().on();
                    });
                }
            }
            else {
                // Unhandled fire-and-forget method
            }
        }
        using SetSpeedLimiterRetType = decltype(std::declval<vehicle_supervisor::skeleton::VehicleSupervisorSkeleton&>().SetSpeedLimiter(std::declval<const float&>(), std::declval<const bool&>()));

        SetSpeedLimiterRetType SetSpeedLimiter(const float& max_kmh, const bool& active) override {
            using MethodTag = ::reaktar::tags::vehicle_supervisor::methods::SetSpeedLimiter;
            if constexpr (has_method_handler_v<Derived, MethodTag, const float&, const bool&> ||
                          has_method_handler_v<Derived, MethodTag, float, bool>) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, max_kmh, active))>) {
                        actor_->self().on(MethodTag{}, max_kmh, active);
                        return result_adapter<SetSpeedLimiterRetType, void>::adapt();
                    } else {
                        return result_adapter<SetSpeedLimiterRetType, decltype(actor_->self().on(MethodTag{}, max_kmh, active))>::adapt(
                            actor_->self().on(MethodTag{}, max_kmh, active)
                        );
                    }
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(actor_->execution_policy_.mutex());
                    if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, max_kmh, active))>) {
                        actor_->self().on(MethodTag{}, max_kmh, active);
                        return result_adapter<SetSpeedLimiterRetType, void>::adapt();
                    } else {
                        return result_adapter<SetSpeedLimiterRetType, decltype(actor_->self().on(MethodTag{}, max_kmh, active))>::adapt(
                            actor_->self().on(MethodTag{}, max_kmh, active)
                        );
                    }
                } else {
                    return actor_->execution_policy_.execute([&]() -> SetSpeedLimiterRetType {
                        if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, max_kmh, active))>) {
                            actor_->self().on(MethodTag{}, max_kmh, active);
                            return result_adapter<SetSpeedLimiterRetType, void>::adapt();
                        } else {
                            return result_adapter<SetSpeedLimiterRetType, decltype(actor_->self().on(MethodTag{}, max_kmh, active))>::adapt(
                                actor_->self().on(MethodTag{}, max_kmh, active)
                            );
                        }
                    });
                }
            }
            else if constexpr (has_direct_method_handler_v<Derived, const float&, const bool&> ||
                               has_direct_method_handler_v<Derived, float, bool>) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    if constexpr (std::is_void_v<decltype(actor_->self().on(max_kmh, active))>) {
                        actor_->self().on(max_kmh, active);
                        return result_adapter<SetSpeedLimiterRetType, void>::adapt();
                    } else {
                        return result_adapter<SetSpeedLimiterRetType, decltype(actor_->self().on(max_kmh, active))>::adapt(
                            actor_->self().on(max_kmh, active)
                        );
                    }
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(actor_->execution_policy_.mutex());
                    if constexpr (std::is_void_v<decltype(actor_->self().on(max_kmh, active))>) {
                        actor_->self().on(max_kmh, active);
                        return result_adapter<SetSpeedLimiterRetType, void>::adapt();
                    } else {
                        return result_adapter<SetSpeedLimiterRetType, decltype(actor_->self().on(max_kmh, active))>::adapt(
                            actor_->self().on(max_kmh, active)
                        );
                    }
                } else {
                    return actor_->execution_policy_.execute([&]() -> SetSpeedLimiterRetType {
                        if constexpr (std::is_void_v<decltype(actor_->self().on(max_kmh, active))>) {
                            actor_->self().on(max_kmh, active);
                            return result_adapter<SetSpeedLimiterRetType, void>::adapt();
                        } else {
                            return result_adapter<SetSpeedLimiterRetType, decltype(actor_->self().on(max_kmh, active))>::adapt(
                                actor_->self().on(max_kmh, active)
                            );
                        }
                    });
                }
            }
            else {
                return result_adapter<SetSpeedLimiterRetType, void>::adapt();
            }
        }
        using TriggerDiagnosticRetType = decltype(std::declval<vehicle_supervisor::skeleton::VehicleSupervisorSkeleton&>().TriggerDiagnostic(std::declval<const uint32_t&>()));

        TriggerDiagnosticRetType TriggerDiagnostic(const uint32_t& code) override {
            using MethodTag = ::reaktar::tags::vehicle_supervisor::methods::TriggerDiagnostic;
            if constexpr (has_method_handler_v<Derived, MethodTag, const uint32_t&> ||
                          has_method_handler_v<Derived, MethodTag, uint32_t>) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, code))>) {
                        actor_->self().on(MethodTag{}, code);
                        return result_adapter<TriggerDiagnosticRetType, void>::adapt();
                    } else {
                        return result_adapter<TriggerDiagnosticRetType, decltype(actor_->self().on(MethodTag{}, code))>::adapt(
                            actor_->self().on(MethodTag{}, code)
                        );
                    }
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(actor_->execution_policy_.mutex());
                    if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, code))>) {
                        actor_->self().on(MethodTag{}, code);
                        return result_adapter<TriggerDiagnosticRetType, void>::adapt();
                    } else {
                        return result_adapter<TriggerDiagnosticRetType, decltype(actor_->self().on(MethodTag{}, code))>::adapt(
                            actor_->self().on(MethodTag{}, code)
                        );
                    }
                } else {
                    return actor_->execution_policy_.execute([&]() -> TriggerDiagnosticRetType {
                        if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, code))>) {
                            actor_->self().on(MethodTag{}, code);
                            return result_adapter<TriggerDiagnosticRetType, void>::adapt();
                        } else {
                            return result_adapter<TriggerDiagnosticRetType, decltype(actor_->self().on(MethodTag{}, code))>::adapt(
                                actor_->self().on(MethodTag{}, code)
                            );
                        }
                    });
                }
            }
            else if constexpr (has_direct_method_handler_v<Derived, const uint32_t&> ||
                               has_direct_method_handler_v<Derived, uint32_t>) {
                static_assert(!sizeof(Derived*), "reaktar::on() collision: RPC method argument signature is shared across multiple methods. You must specify the method tag: on(MethodTag, ...).");
            }
            else {
                return result_adapter<TriggerDiagnosticRetType, void>::adapt();
            }
        }
    };

    SupervisorPortSkeletonAdapter supervisorport_skeleton_;

    vehicle_supervisor::skeleton::VehicleSupervisorSkeleton& get_supervisorport_skeleton() { return supervisorport_skeleton_; }

    using legal_signatures = std::tuple<
        reaktar::sig<>,
        reaktar::sig<::reaktar::tags::vehicle_supervisor::methods::ResetTripMeter>,
        reaktar::sig<uint32_t>,
        reaktar::sig<vehicle_data::DriveMode>,
        reaktar::sig<::reaktar::tags::vehicle_supervisor::fields::CalibrationKey, uint32_t>,
        reaktar::sig<::reaktar::tags::vehicle_supervisor::fields::CurrentDriveMode, vehicle_data::DriveMode>,
        reaktar::sig<::reaktar::tags::vehicle_supervisor::methods::CalibrateOdometer, uint32_t>,
        reaktar::sig<::reaktar::tags::vehicle_supervisor::methods::TriggerDiagnostic, uint32_t>,
        reaktar::sig<float, bool>,
        reaktar::sig<::reaktar::tags::vehicle_supervisor::methods::SetSpeedLimiter, float, bool>
    >;

    explicit TelemetryActor(
        reaktar::InstanceSpecifier supervisorport_instance = reaktar::InstanceSpecifier("Telemetry/RootSwComponent/SupervisorPort"),
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent
    )
        : TelemetryActorBase()
        , supervisorport_skeleton_(this, std::move(supervisorport_instance), mode)
    {
        if constexpr (::reaktar::strict_validation_enabled) {
            using LegalSignaturesTuple = legal_signatures;

            static_assert(!reaktar::has_rogue_handler_v<Derived, LegalSignaturesTuple
                , bool
                , float
                , uint32_t
                , vehicle_data::DriveMode
                , ::reaktar::tags::vehicle_supervisor::fields::CalibrationKey
                , ::reaktar::tags::vehicle_supervisor::fields::CurrentDriveMode
                , ::reaktar::tags::vehicle_supervisor::methods::CalibrateOdometer
                , ::reaktar::tags::vehicle_supervisor::methods::ResetTripMeter
                , ::reaktar::tags::vehicle_supervisor::methods::SetSpeedLimiter
                , ::reaktar::tags::vehicle_supervisor::methods::TriggerDiagnostic
            >,
            "\n"
            "====================================================================================\n"
            " Reaktar Compile Error: Rogue/orphan on(...) handler detected in Telemetry!\n"
            " You declared an on(...) method taking a parameter type or signature combination that\n"
            " does NOT exist in this ARXML interface (or is a typo/dead handler).\n"
            " To disable strict ARXML compile-time validation, build without -DREAKTAR_STRICT_VALIDATION\n"
            "====================================================================================\n"
            );
        }
    }

    virtual ~TelemetryActor() = default;

    Derived& self() { return static_cast<Derived&>(*this); }
    // ------------------------------------------------------------------------
    // OUTBOUND: emit<Tag>(args...) OR untagged emit(val)
    // ------------------------------------------------------------------------
    template <typename Tag, typename... Args>
    auto emit(Args&&... args) {
        if constexpr (std::is_same_v<Tag, vehicle_supervisor::events::EmergencyAlert>) {
            supervisorport_skeleton_.EmergencyAlert.Send(std::forward<Args>(args)...);
            return ::reaktar::EmitStatus{true};
        }
        else {
            static_assert(!sizeof(Tag*), "reaktar: emit called with unknown tag!");
        }
    }

    template <typename Tag, typename... Args>
    auto call(Args&&... args) {
        return emit<Tag>(std::forward<Args>(args)...);
    }

    template <typename... Args>
    auto emit(Args&&... args) {
        if constexpr (sizeof...(Args) == 1) {
            using PayloadType = std::decay_t<typename std::tuple_element<0, std::tuple<Args...>>::type>;
            if constexpr (std::is_same_v<PayloadType, vehicle_data::EmergencyAlert>) {
                supervisorport_skeleton_.EmergencyAlert.Send(std::forward<Args>(args)...);
                return ::reaktar::EmitStatus{true};
            }
            else {
                static_assert(!sizeof...(Args), "reaktar: emit(payload) failed! The payload type is not produced by any skeleton event, field, or single-arg RPC method in this Actor.");
            }
        }
        else {
            static_assert(!sizeof...(Args), "reaktar: emit(args...) failed! The argument list does not match any unique proxy RPC method in this Actor. Use emit<Tag>(args...) if ambiguous.");
        }
    }
    void start() {
        bind_skeleton_fields();

        supervisorport_skeleton_.OfferService();

    }

    void stop() {
        supervisorport_skeleton_.StopOfferService();
    }

private:

    void bind_skeleton_fields() {
        if constexpr (has_on_field_set_v<Derived, vehicle_supervisor::fields::CalibrationKey, uint32_t>) {
            supervisorport_skeleton_.CalibrationKey.RegisterSetHandler([this](const uint32_t& val) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    return result_adapter<reaktar::Future<uint32_t>, decltype(self().on_set(vehicle_supervisor::fields::CalibrationKey{}, val))>::adapt(
                        self().on_set(vehicle_supervisor::fields::CalibrationKey{}, val)
                    );
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                    return result_adapter<reaktar::Future<uint32_t>, decltype(self().on_set(vehicle_supervisor::fields::CalibrationKey{}, val))>::adapt(
                        self().on_set(vehicle_supervisor::fields::CalibrationKey{}, val)
                    );
                } else {
                    return this->execution_policy_.execute([&] {
                        return result_adapter<reaktar::Future<uint32_t>, decltype(self().on_set(vehicle_supervisor::fields::CalibrationKey{}, val))>::adapt(
                            self().on_set(vehicle_supervisor::fields::CalibrationKey{}, val)
                        );
                    });
                }
            });
        }
        else if constexpr (has_on_direct_field_set_v<Derived, uint32_t>) {
            supervisorport_skeleton_.CalibrationKey.RegisterSetHandler([this](const uint32_t& val) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    return result_adapter<reaktar::Future<uint32_t>, decltype(self().on_set(val))>::adapt(
                        self().on_set(val)
                    );
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                    return result_adapter<reaktar::Future<uint32_t>, decltype(self().on_set(val))>::adapt(
                        self().on_set(val)
                    );
                } else {
                    return this->execution_policy_.execute([&] {
                        return result_adapter<reaktar::Future<uint32_t>, decltype(self().on_set(val))>::adapt(
                            self().on_set(val)
                        );
                    });
                }
            });
        }
        // Initialise field value before OfferService (required by AUTOSAR Adaptive caching/notifier semantics)
        supervisorport_skeleton_.CurrentDriveMode.Update({});
        if constexpr (has_on_field_set_v<Derived, vehicle_supervisor::fields::CurrentDriveMode, vehicle_data::DriveMode>) {
            supervisorport_skeleton_.CurrentDriveMode.RegisterSetHandler([this](const vehicle_data::DriveMode& val) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    return result_adapter<reaktar::Future<vehicle_data::DriveMode>, decltype(self().on_set(vehicle_supervisor::fields::CurrentDriveMode{}, val))>::adapt(
                        self().on_set(vehicle_supervisor::fields::CurrentDriveMode{}, val)
                    );
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                    return result_adapter<reaktar::Future<vehicle_data::DriveMode>, decltype(self().on_set(vehicle_supervisor::fields::CurrentDriveMode{}, val))>::adapt(
                        self().on_set(vehicle_supervisor::fields::CurrentDriveMode{}, val)
                    );
                } else {
                    return this->execution_policy_.execute([&] {
                        return result_adapter<reaktar::Future<vehicle_data::DriveMode>, decltype(self().on_set(vehicle_supervisor::fields::CurrentDriveMode{}, val))>::adapt(
                            self().on_set(vehicle_supervisor::fields::CurrentDriveMode{}, val)
                        );
                    });
                }
            });
        }
        else if constexpr (has_on_direct_field_set_v<Derived, vehicle_data::DriveMode>) {
            supervisorport_skeleton_.CurrentDriveMode.RegisterSetHandler([this](const vehicle_data::DriveMode& val) {
                if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::DirectExecution>) {
                    return result_adapter<reaktar::Future<vehicle_data::DriveMode>, decltype(self().on_set(val))>::adapt(
                        self().on_set(val)
                    );
                } else if constexpr (std::is_same_v<ExecutionPolicy, ::reaktar::SynchronizedExecution>) {
                    std::lock_guard<std::mutex> lock(this->execution_policy_.mutex());
                    return result_adapter<reaktar::Future<vehicle_data::DriveMode>, decltype(self().on_set(val))>::adapt(
                        self().on_set(val)
                    );
                } else {
                    return this->execution_policy_.execute([&] {
                        return result_adapter<reaktar::Future<vehicle_data::DriveMode>, decltype(self().on_set(val))>::adapt(
                            self().on_set(val)
                        );
                    });
                }
            });
        }
        // Initialise field value before OfferService (required by AUTOSAR Adaptive caching/notifier semantics)
        supervisorport_skeleton_.HardwareRevision.Update({});
    }

};

// Convenience alias mapping Component name to Executable Actor
template <typename Derived, typename ExecutionPolicy = ::reaktar::DirectExecution>
using TelemetryAppActor = TelemetryActor<Derived, ExecutionPolicy>;
using TelemetryAppActorBase = TelemetryActorBase;

// Convenience aliases for specifying ExecutionPolicy first
template <typename Derived, typename ExecutionPolicy = ::reaktar::SynchronizedExecution>
using TelemetryActorWithPolicy = TelemetryActor<Derived, ExecutionPolicy>;

template <typename Derived, typename ExecutionPolicy = ::reaktar::SynchronizedExecution>
using TelemetryAppActorWithPolicy = TelemetryActor<Derived, ExecutionPolicy>;

} // namespace generated
} // namespace reaktar