// ==============================================================================
// Reaktar - Reactive Actor Framework for AUTOSAR Adaptive
// Part of the Pyarx project: https://github.com/pyarxlab/reaktar
//
// Generated Actor: VehicleSupervisorActor
// Source ARXML component: VehicleSupervisorApp
// DO NOT EDIT DIRECTLY - GENERATED BY reaktar scripts/generate_actor.py
// ==============================================================================

#pragma once

#include "vehicle_supervisor/vehiclesupervisor_skeleton.h"
#include "body_control/bodycontrol_proxy.h"
#include "powertrain/powertrain_proxy.h"
#include "reaktar/tags.hpp"
#include "reaktar/traits.hpp"
#include "reaktar/proxy_slot.hpp"
#include "reaktar/actor_base.hpp"
#include <string>
#include <utility>
#include <optional>
#include <chrono>

namespace reaktar {
namespace generated {

/**
 * @brief Non-templated Actor Base for VehicleSupervisor
 *
 * Provides pure ergonomic Tag aliases and unqualified `emit(...)`.
 * Does NOT inherit from Skeletons to completely eliminate name collisions/shadowing!
 */
class VehicleSupervisorActorBase
{
public:
    // ------------------------------------------------------------------------
    // Ergonomic Tag Aliases (brought directly into Actor class scope)
    // ------------------------------------------------------------------------
    using CabinSensors = ::reaktar::tags::powertrain::events::CabinSensors;
    using CalibrateOdometer = ::reaktar::tags::vehicle_supervisor::methods::CalibrateOdometer;
    using CalibrationKey = ::reaktar::tags::vehicle_supervisor::fields::CalibrationKey;
    using CurrentDriveMode = ::reaktar::tags::vehicle_supervisor::fields::CurrentDriveMode;
    using EmergencyAlert = ::reaktar::tags::vehicle_supervisor::events::EmergencyAlert;
    using FlashLights = ::reaktar::tags::body_control::methods::FlashLights;
    using HardwareRevision = ::reaktar::tags::vehicle_supervisor::fields::HardwareRevision;
    using LockDoors = ::reaktar::tags::body_control::methods::LockDoors;
    using OutsideAirQuality = ::reaktar::tags::body_control::fields::OutsideAirQuality;
    using RainSensorLevel = ::reaktar::tags::body_control::fields::RainSensorLevel;
    using ResetTripMeter = ::reaktar::tags::vehicle_supervisor::methods::ResetTripMeter;
    using SetSpeedLimiter = ::reaktar::tags::vehicle_supervisor::methods::SetSpeedLimiter;
    using TargetCabinTemperature = ::reaktar::tags::body_control::fields::TargetCabinTemperature;
    using TriggerDiagnostic = ::reaktar::tags::vehicle_supervisor::methods::TriggerDiagnostic;
    using VehicleSpeed = ::reaktar::tags::powertrain::events::VehicleSpeed;
    using WindowPosition = ::reaktar::tags::body_control::fields::WindowPosition;

    VehicleSupervisorActorBase() = default;
    virtual ~VehicleSupervisorActorBase() = default;

    body_control::proxy::BodyControlProxy* get_body_control_proxy() const noexcept { return body_control_slot_.get(); }
    bool is_body_control_ready() const noexcept { return body_control_slot_.is_available(); }
    reaktar::ProxyLease<body_control::proxy::BodyControlProxy> acquire_body_control_proxy() { return body_control_slot_.acquire("body_control"); }
    powertrain::proxy::PowertrainProxy* get_powertrain_proxy() const noexcept { return powertrain_slot_.get(); }
    bool is_powertrain_ready() const noexcept { return powertrain_slot_.is_available(); }
    reaktar::ProxyLease<powertrain::proxy::PowertrainProxy> acquire_powertrain_proxy() { return powertrain_slot_.acquire("powertrain"); }

    static constexpr size_t kConsumedProxyCount = 2;

    /**
     * @brief Check whether all required service proxies have been resolved and published.
     * Always returns true if this Actor consumes 0 services.
     */
    bool is_ready() const noexcept {
        return readiness_.is_ready([this] {
            return (body_control_slot_.is_available() && powertrain_slot_.is_available());
        });
    }

    /**
     * @brief Block until all required service proxies have been resolved and published.
     * Fully zero-cost: if this Actor consumes 0 services, returns true immediately without locks or cv.
     */
    bool wait_until_ready() {
        return readiness_.wait_until_ready([this] {
            return (body_control_slot_.is_available() && powertrain_slot_.is_available());
        });
    }

    /**
     * @brief Block with a timeout until all required service proxies have been resolved and published.
     * Returns true if ready, false if timeout expired.
     */
    template <typename Rep, typename Period>
    bool wait_until_ready(const std::chrono::duration<Rep, Period>& timeout) {
        return readiness_.wait_until_ready([this] {
            return (body_control_slot_.is_available() && powertrain_slot_.is_available());
        }, timeout);
    }

protected:
    void notify_proxy_resolved() {
        readiness_.notify_resolved();
    }

    reaktar::ReadinessTracker<kConsumedProxyCount> readiness_{};
    reaktar::ProxySlot<body_control::proxy::BodyControlProxy> body_control_slot_{};
    std::optional<ara::com::FindServiceHandle> body_control_find_handle_{std::nullopt};
    reaktar::ProxySlot<powertrain::proxy::PowertrainProxy> powertrain_slot_{};
    std::optional<ara::com::FindServiceHandle> powertrain_find_handle_{std::nullopt};
};
/**
 * @brief Code-generated CRTP Actor for VehicleSupervisor
 */
template <typename Derived, reaktar::StrictValidation Validation = reaktar::StrictValidation::kEnabled>
class VehicleSupervisorActor : public VehicleSupervisorActorBase {
public:
    using Base = VehicleSupervisorActorBase;
    using Base::get_body_control_proxy;
    using Base::get_powertrain_proxy;

    // Skeleton Adapter for VehicleSupervisorInterface
    class SupervisorPortSkeletonAdapter : public vehicle_supervisor::skeleton::VehicleSupervisorSkeleton {
        VehicleSupervisorActor* actor_;
    public:
        explicit SupervisorPortSkeletonAdapter(
            VehicleSupervisorActor* a,
            ara::core::InstanceSpecifier instance_spec,
            ara::com::MethodCallProcessingMode mode
        )
            : vehicle_supervisor::skeleton::VehicleSupervisorSkeleton(std::move(instance_spec), mode), actor_(a) {}

        // Skeleton RPC Method Overrides
        using CalibrateOdometerRetType = decltype(std::declval<vehicle_supervisor::skeleton::VehicleSupervisorSkeleton&>().CalibrateOdometer(std::declval<const uint32_t&>()));

        CalibrateOdometerRetType CalibrateOdometer(const uint32_t& current_km) override {
            using MethodTag = ::reaktar::tags::vehicle_supervisor::methods::CalibrateOdometer;
            if constexpr (has_method_handler_v<Derived, MethodTag, const uint32_t&> ||
                          has_method_handler_v<Derived, MethodTag, uint32_t>) {
                if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, current_km))>) {
                    actor_->self().on(MethodTag{}, current_km);
                    return result_adapter<CalibrateOdometerRetType, void>::adapt();
                } else {
                    return result_adapter<CalibrateOdometerRetType, decltype(actor_->self().on(MethodTag{}, current_km))>::adapt(
                        actor_->self().on(MethodTag{}, current_km)
                    );
                }
            }
            else if constexpr (has_direct_method_handler_v<Derived, const uint32_t&> ||
                               has_direct_method_handler_v<Derived, uint32_t>) {
                static_assert(!sizeof(Derived*), "reaktar::on() collision: RPC method argument signature is shared across multiple methods. You must specify the method tag: on(MethodTag, ...).");
            }
            else {
                return result_adapter<CalibrateOdometerRetType, void>::adapt();
            }
        }
        void ResetTripMeter() override {
            using MethodTag = ::reaktar::tags::vehicle_supervisor::methods::ResetTripMeter;
            if constexpr (has_method_handler_v<Derived, MethodTag> ||
                          has_method_handler_v<Derived, MethodTag>) {
                actor_->self().on(MethodTag{});
            }
            else if constexpr (has_direct_method_handler_v<Derived> ||
                               has_direct_method_handler_v<Derived>) {
                actor_->self().on();
            }
            else {
                // Unhandled fire-and-forget method
            }
        }
        using SetSpeedLimiterRetType = decltype(std::declval<vehicle_supervisor::skeleton::VehicleSupervisorSkeleton&>().SetSpeedLimiter(std::declval<const float&>(), std::declval<const bool&>()));

        SetSpeedLimiterRetType SetSpeedLimiter(const float& max_kmh, const bool& active) override {
            using MethodTag = ::reaktar::tags::vehicle_supervisor::methods::SetSpeedLimiter;
            if constexpr (has_method_handler_v<Derived, MethodTag, const float&, const bool&> ||
                          has_method_handler_v<Derived, MethodTag, float, bool>) {
                if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, max_kmh, active))>) {
                    actor_->self().on(MethodTag{}, max_kmh, active);
                    return result_adapter<SetSpeedLimiterRetType, void>::adapt();
                } else {
                    return result_adapter<SetSpeedLimiterRetType, decltype(actor_->self().on(MethodTag{}, max_kmh, active))>::adapt(
                        actor_->self().on(MethodTag{}, max_kmh, active)
                    );
                }
            }
            else if constexpr (has_direct_method_handler_v<Derived, const float&, const bool&> ||
                               has_direct_method_handler_v<Derived, float, bool>) {
                if constexpr (std::is_void_v<decltype(actor_->self().on(max_kmh, active))>) {
                    actor_->self().on(max_kmh, active);
                    return result_adapter<SetSpeedLimiterRetType, void>::adapt();
                } else {
                    return result_adapter<SetSpeedLimiterRetType, decltype(actor_->self().on(max_kmh, active))>::adapt(
                        actor_->self().on(max_kmh, active)
                    );
                }
            }
            else {
                return result_adapter<SetSpeedLimiterRetType, void>::adapt();
            }
        }
        using TriggerDiagnosticRetType = decltype(std::declval<vehicle_supervisor::skeleton::VehicleSupervisorSkeleton&>().TriggerDiagnostic(std::declval<const uint32_t&>()));

        TriggerDiagnosticRetType TriggerDiagnostic(const uint32_t& code) override {
            using MethodTag = ::reaktar::tags::vehicle_supervisor::methods::TriggerDiagnostic;
            if constexpr (has_method_handler_v<Derived, MethodTag, const uint32_t&> ||
                          has_method_handler_v<Derived, MethodTag, uint32_t>) {
                if constexpr (std::is_void_v<decltype(actor_->self().on(MethodTag{}, code))>) {
                    actor_->self().on(MethodTag{}, code);
                    return result_adapter<TriggerDiagnosticRetType, void>::adapt();
                } else {
                    return result_adapter<TriggerDiagnosticRetType, decltype(actor_->self().on(MethodTag{}, code))>::adapt(
                        actor_->self().on(MethodTag{}, code)
                    );
                }
            }
            else if constexpr (has_direct_method_handler_v<Derived, const uint32_t&> ||
                               has_direct_method_handler_v<Derived, uint32_t>) {
                static_assert(!sizeof(Derived*), "reaktar::on() collision: RPC method argument signature is shared across multiple methods. You must specify the method tag: on(MethodTag, ...).");
            }
            else {
                return result_adapter<TriggerDiagnosticRetType, void>::adapt();
            }
        }
    };

    SupervisorPortSkeletonAdapter supervisorport_skeleton_;

    vehicle_supervisor::skeleton::VehicleSupervisorSkeleton& get_supervisorport_skeleton() { return supervisorport_skeleton_; }

    explicit VehicleSupervisorActor(
        ara::core::InstanceSpecifier supervisorport_instance = ara::core::InstanceSpecifier("VehicleSupervisor/RootSwComponent/SupervisorPort"),
        ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent
    )
        : VehicleSupervisorActorBase()
        , supervisorport_skeleton_(this, std::move(supervisorport_instance), mode)
    {
        if constexpr (Validation == reaktar::StrictValidation::kEnabled) {
            using LegalSignaturesTuple = std::tuple<
                reaktar::sig<>,
                reaktar::sig<::reaktar::tags::vehicle_supervisor::methods::ResetTripMeter>,
                reaktar::sig<float>,
                reaktar::sig<uint32_t>,
                reaktar::sig<vehicle_data::CabinSensorData>,
                reaktar::sig<vehicle_data::DriveMode>,
                reaktar::sig<vehicle_data::SpeedData>,
                reaktar::sig<::reaktar::tags::body_control::fields::OutsideAirQuality, uint32_t>,
                reaktar::sig<::reaktar::tags::body_control::fields::RainSensorLevel, uint32_t>,
                reaktar::sig<::reaktar::tags::body_control::fields::TargetCabinTemperature, float>,
                reaktar::sig<::reaktar::tags::body_control::fields::WindowPosition, uint32_t>,
                reaktar::sig<::reaktar::tags::powertrain::events::CabinSensors, vehicle_data::CabinSensorData>,
                reaktar::sig<::reaktar::tags::powertrain::events::VehicleSpeed, vehicle_data::SpeedData>,
                reaktar::sig<::reaktar::tags::vehicle_supervisor::fields::CalibrationKey, uint32_t>,
                reaktar::sig<::reaktar::tags::vehicle_supervisor::fields::CurrentDriveMode, vehicle_data::DriveMode>,
                reaktar::sig<::reaktar::tags::vehicle_supervisor::methods::CalibrateOdometer, uint32_t>,
                reaktar::sig<::reaktar::tags::vehicle_supervisor::methods::TriggerDiagnostic, uint32_t>,
                reaktar::sig<float, bool>,
                reaktar::sig<::reaktar::tags::vehicle_supervisor::methods::SetSpeedLimiter, float, bool>
            >;

            static_assert(!reaktar::has_rogue_handler_v<Derived, LegalSignaturesTuple
                , bool
                , float
                , uint32_t
                , vehicle_data::CabinSensorData
                , vehicle_data::DriveMode
                , vehicle_data::SpeedData
                , ::reaktar::tags::body_control::fields::OutsideAirQuality
                , ::reaktar::tags::body_control::fields::RainSensorLevel
                , ::reaktar::tags::body_control::fields::TargetCabinTemperature
                , ::reaktar::tags::body_control::fields::WindowPosition
                , ::reaktar::tags::powertrain::events::CabinSensors
                , ::reaktar::tags::powertrain::events::VehicleSpeed
                , ::reaktar::tags::vehicle_supervisor::fields::CalibrationKey
                , ::reaktar::tags::vehicle_supervisor::fields::CurrentDriveMode
                , ::reaktar::tags::vehicle_supervisor::methods::CalibrateOdometer
                , ::reaktar::tags::vehicle_supervisor::methods::ResetTripMeter
                , ::reaktar::tags::vehicle_supervisor::methods::SetSpeedLimiter
                , ::reaktar::tags::vehicle_supervisor::methods::TriggerDiagnostic
            >,
            "\n"
            "====================================================================================\n"
            " ReaktAR Compile Error: Rogue/orphan on(...) handler detected in VehicleSupervisor!\n"
            " You declared an on(...) method taking a parameter type or signature combination that\n"
            " does NOT exist in this ARXML interface (or is a typo/dead handler).\n"
            " To disable strict ARXML compile-time validation, inherit from:\n"
            "   reaktar::generated::VehicleSupervisorActor<VehicleSupervisor, reaktar::StrictValidation::kDisabled>\n"
            "====================================================================================\n"
            );
        }
    }

    virtual ~VehicleSupervisorActor() = default;

    Derived& self() { return static_cast<Derived&>(*this); }
    // ------------------------------------------------------------------------
    // OUTBOUND: emit<Tag>(args...) OR untagged emit(val)
    // ------------------------------------------------------------------------
    template <typename Tag, typename... Args>
    auto emit(Args&&... args) {
        if constexpr (std::is_same_v<Tag, vehicle_supervisor::events::EmergencyAlert>) {
            supervisorport_skeleton_.EmergencyAlert.Send(std::forward<Args>(args)...);
            return ::reaktar::EmitStatus{true};
        }
        else if constexpr (std::is_same_v<Tag, ::reaktar::tags::body_control::methods::FlashLights>) {
            auto proxy_lease = this->body_control_slot_.acquire("body_control");
            if (proxy_lease) {
                proxy_lease->FlashLights(std::forward<Args>(args)...);
                return ::reaktar::EmitStatus{true};
            }
            return ::reaktar::EmitStatus{false};
        }
        else if constexpr (std::is_same_v<Tag, ::reaktar::tags::body_control::methods::LockDoors>) {
            auto proxy_lease = this->body_control_slot_.acquire("body_control");
            using AsyncResType = decltype(make_async_result(proxy_lease->LockDoors(std::forward<Args>(args)...)));
            if (proxy_lease) {
                return make_async_result(proxy_lease->LockDoors(std::forward<Args>(args)...));
            }
            return AsyncResType::Failed();
        }
        else if constexpr (std::is_same_v<Tag, body_control::fields::TargetCabinTemperature>) {
            auto proxy_lease = this->body_control_slot_.acquire("body_control");
            using AsyncResType = decltype(make_async_result(proxy_lease->TargetCabinTemperature.Set(std::forward<Args>(args)...)));
            if (proxy_lease) {
                return make_async_result(proxy_lease->TargetCabinTemperature.Set(std::forward<Args>(args)...));
            }
            return AsyncResType::Failed();
        }
        else if constexpr (std::is_same_v<Tag, body_control::fields::WindowPosition>) {
            auto proxy_lease = this->body_control_slot_.acquire("body_control");
            using AsyncResType = decltype(make_async_result(proxy_lease->WindowPosition.Set(std::forward<Args>(args)...)));
            if (proxy_lease) {
                return make_async_result(proxy_lease->WindowPosition.Set(std::forward<Args>(args)...));
            }
            return AsyncResType::Failed();
        }
        else {
            static_assert(!sizeof(Tag*), "reaktar: emit called with unknown tag!");
        }
    }

    template <typename Tag, typename... Args>
    auto call(Args&&... args) {
        return emit<Tag>(std::forward<Args>(args)...);
    }

    template <typename... Args>
    auto emit(Args&&... args) {
        if constexpr (sizeof...(Args) == 1) {
            using PayloadType = std::decay_t<typename std::tuple_element<0, std::tuple<Args...>>::type>;
            if constexpr (std::is_same_v<PayloadType, vehicle_data::EmergencyAlert>) {
                supervisorport_skeleton_.EmergencyAlert.Send(std::forward<Args>(args)...);
                return ::reaktar::EmitStatus{true};
            }
            else if constexpr (std::is_same_v<PayloadType, bool>) {
                auto proxy_lease = this->body_control_slot_.acquire("body_control");
                using AsyncResType = decltype(make_async_result(proxy_lease->LockDoors(std::forward<Args>(args)...)));
                if (proxy_lease) {
                    return make_async_result(proxy_lease->LockDoors(std::forward<Args>(args)...));
                }
                return AsyncResType::Failed();
            }
            else {
                static_assert(!sizeof...(Args), "reaktar: emit(payload) failed! The payload type is not produced by any skeleton event, field, or single-arg RPC method in this Actor.");
            }
        }
        else {
            using SigTuple [[maybe_unused]] = std::tuple<std::decay_t<Args>...>;
            if constexpr (std::is_same_v<SigTuple, std::tuple<uint32_t, uint32_t>>) {
                auto proxy_lease = this->body_control_slot_.acquire("body_control");
                if (proxy_lease) {
                    proxy_lease->FlashLights(std::forward<Args>(args)...);
                    return ::reaktar::EmitStatus{true};
                }
                return ::reaktar::EmitStatus{false};
            }
            else {
                static_assert(!sizeof...(Args), "reaktar: emit(args...) failed! The argument list does not match any unique proxy RPC method in this Actor. Use emit<Tag>(args...) if ambiguous.");
            }
        }
    }
    void start() {
        bind_skeleton_fields();

        supervisorport_skeleton_.OfferService();

        this->body_control_find_handle_ = body_control::proxy::BodyControlProxy::StartFindService(
            [this](ara::com::ServiceHandleContainer<body_control::proxy::BodyControlProxy::HandleType> handles, ara::com::FindServiceHandle) {
                if (handles.empty()) {
                    teardown_body_control_proxy();
                } else {
                    if (auto* current = this->body_control_slot_.get()) {
                        if (current->GetHandle() == handles[0]) {
                            return; // Same handle, already active
                        }
                        teardown_body_control_proxy();
                    }
                    auto new_proxy = std::make_unique<body_control::proxy::BodyControlProxy>(handles[0]);
                    bind_body_control_events(new_proxy.get());
                    bind_body_control_fields(new_proxy.get());
                    this->body_control_slot_.publish(std::move(new_proxy));
                    this->notify_proxy_resolved();
                }
            },
            ara::core::InstanceSpecifier("VehicleSupervisor/RootSwComponent/BodyControlIn")
        );
        this->powertrain_find_handle_ = powertrain::proxy::PowertrainProxy::StartFindService(
            [this](ara::com::ServiceHandleContainer<powertrain::proxy::PowertrainProxy::HandleType> handles, ara::com::FindServiceHandle) {
                if (handles.empty()) {
                    teardown_powertrain_proxy();
                } else {
                    if (auto* current = this->powertrain_slot_.get()) {
                        if (current->GetHandle() == handles[0]) {
                            return; // Same handle, already active
                        }
                        teardown_powertrain_proxy();
                    }
                    auto new_proxy = std::make_unique<powertrain::proxy::PowertrainProxy>(handles[0]);
                    bind_powertrain_events(new_proxy.get());
                    bind_powertrain_fields(new_proxy.get());
                    this->powertrain_slot_.publish(std::move(new_proxy));
                    this->notify_proxy_resolved();
                }
            },
            ara::core::InstanceSpecifier("VehicleSupervisor/RootSwComponent/PowertrainIn")
        );
    }

    void stop() {
        supervisorport_skeleton_.StopOfferService();
        if (this->body_control_find_handle_.has_value()) {
            body_control::proxy::BodyControlProxy::StopFindService(*this->body_control_find_handle_);
            this->body_control_find_handle_.reset();
        }
        teardown_body_control_proxy();
        if (this->powertrain_find_handle_.has_value()) {
            powertrain::proxy::PowertrainProxy::StopFindService(*this->powertrain_find_handle_);
            this->powertrain_find_handle_.reset();
        }
        teardown_powertrain_proxy();
    }

private:
    void teardown_body_control_proxy() {
        if (auto* p = this->body_control_slot_.get()) {
            p->OutsideAirQuality.Unsubscribe();
            p->RainSensorLevel.Unsubscribe();
            p->TargetCabinTemperature.Unsubscribe();
            p->WindowPosition.Unsubscribe();
            this->body_control_slot_.reset();
        }
    }
    void teardown_powertrain_proxy() {
        if (auto* p = this->powertrain_slot_.get()) {
            p->CabinSensors.Unsubscribe();
            p->VehicleSpeed.Unsubscribe();
            this->powertrain_slot_.reset();
        }
    }

    void bind_skeleton_fields() {
        if constexpr (has_on_field_set_v<Derived, vehicle_supervisor::fields::CalibrationKey, uint32_t>) {
            supervisorport_skeleton_.CalibrationKey.RegisterSetHandler([this](const uint32_t& val) {
                return result_adapter<uint32_t, decltype(self().on_set(vehicle_supervisor::fields::CalibrationKey{}, val))>::adapt(
                    self().on_set(vehicle_supervisor::fields::CalibrationKey{}, val)
                );
            });
        }
        else if constexpr (has_on_direct_field_set_v<Derived, uint32_t>) {
            supervisorport_skeleton_.CalibrationKey.RegisterSetHandler([this](const uint32_t& val) {
                return result_adapter<uint32_t, decltype(self().on_set(val))>::adapt(
                    self().on_set(val)
                );
            });
        }
        // Initialise field value before OfferService (required by AUTOSAR Adaptive caching/notifier semantics)
        supervisorport_skeleton_.CurrentDriveMode.Update({});
        if constexpr (has_on_field_set_v<Derived, vehicle_supervisor::fields::CurrentDriveMode, vehicle_data::DriveMode>) {
            supervisorport_skeleton_.CurrentDriveMode.RegisterSetHandler([this](const vehicle_data::DriveMode& val) {
                return result_adapter<vehicle_data::DriveMode, decltype(self().on_set(vehicle_supervisor::fields::CurrentDriveMode{}, val))>::adapt(
                    self().on_set(vehicle_supervisor::fields::CurrentDriveMode{}, val)
                );
            });
        }
        else if constexpr (has_on_direct_field_set_v<Derived, vehicle_data::DriveMode>) {
            supervisorport_skeleton_.CurrentDriveMode.RegisterSetHandler([this](const vehicle_data::DriveMode& val) {
                return result_adapter<vehicle_data::DriveMode, decltype(self().on_set(val))>::adapt(
                    self().on_set(val)
                );
            });
        }
        // Initialise field value before OfferService (required by AUTOSAR Adaptive caching/notifier semantics)
        supervisorport_skeleton_.HardwareRevision.Update({});
    }

    void bind_body_control_events(body_control::proxy::BodyControlProxy* proxy) {
        if (!proxy) return;
    }

    void bind_body_control_fields(body_control::proxy::BodyControlProxy* proxy) {
        if (!proxy) return;
        // Field Notifier: OutsideAirQuality (uint32_t)
        if constexpr (has_on_event_v<Derived, body_control::fields::OutsideAirQuality, uint32_t>) {
            proxy->OutsideAirQuality.SetReceiveHandler([this, proxy]() {
                proxy->OutsideAirQuality.GetNewSamples([this](auto&& s) {
                    self().on(body_control::fields::OutsideAirQuality{}, *s);
                });
            });
            proxy->OutsideAirQuality.Subscribe(10);
        }
        else if constexpr (has_on_direct_event_v<Derived, uint32_t>) {
            static_assert(!sizeof(Derived*), "reaktar::on() collision: type 'uint32_t' is shared across multiple incoming channels (events/fields). You must specify the tag: void on(body_control::fields::OutsideAirQuality, const uint32_t& val).");
        }
        // Field Notifier: RainSensorLevel (uint32_t)
        if constexpr (has_on_event_v<Derived, body_control::fields::RainSensorLevel, uint32_t>) {
            proxy->RainSensorLevel.SetReceiveHandler([this, proxy]() {
                proxy->RainSensorLevel.GetNewSamples([this](auto&& s) {
                    self().on(body_control::fields::RainSensorLevel{}, *s);
                });
            });
            proxy->RainSensorLevel.Subscribe(10);
        }
        else if constexpr (has_on_direct_event_v<Derived, uint32_t>) {
            static_assert(!sizeof(Derived*), "reaktar::on() collision: type 'uint32_t' is shared across multiple incoming channels (events/fields). You must specify the tag: void on(body_control::fields::RainSensorLevel, const uint32_t& val).");
        }
        // Field Notifier: TargetCabinTemperature (float)
        if constexpr (has_on_event_v<Derived, body_control::fields::TargetCabinTemperature, float>) {
            proxy->TargetCabinTemperature.SetReceiveHandler([this, proxy]() {
                proxy->TargetCabinTemperature.GetNewSamples([this](auto&& s) {
                    self().on(body_control::fields::TargetCabinTemperature{}, *s);
                });
            });
            proxy->TargetCabinTemperature.Subscribe(10);
        }
        else if constexpr (has_on_direct_event_v<Derived, float>) {
            proxy->TargetCabinTemperature.SetReceiveHandler([this, proxy]() {
                proxy->TargetCabinTemperature.GetNewSamples([this](auto&& s) {
                    self().on(*s);
                });
            });
            proxy->TargetCabinTemperature.Subscribe(10);
        }
        // Field Notifier: WindowPosition (uint32_t)
        if constexpr (has_on_event_v<Derived, body_control::fields::WindowPosition, uint32_t>) {
            proxy->WindowPosition.SetReceiveHandler([this, proxy]() {
                proxy->WindowPosition.GetNewSamples([this](auto&& s) {
                    self().on(body_control::fields::WindowPosition{}, *s);
                });
            });
            proxy->WindowPosition.Subscribe(10);
        }
        else if constexpr (has_on_direct_event_v<Derived, uint32_t>) {
            static_assert(!sizeof(Derived*), "reaktar::on() collision: type 'uint32_t' is shared across multiple incoming channels (events/fields). You must specify the tag: void on(body_control::fields::WindowPosition, const uint32_t& val).");
        }
    }
    void bind_powertrain_events(powertrain::proxy::PowertrainProxy* proxy) {
        if (!proxy) return;
        // Event: CabinSensors (vehicle_data::CabinSensorData)
        if constexpr (has_on_event_v<Derived, powertrain::events::CabinSensors, vehicle_data::CabinSensorData>) {
            proxy->CabinSensors.SetReceiveHandler([this, proxy]() {
                proxy->CabinSensors.GetNewSamples([this](auto&& s) {
                    self().on(powertrain::events::CabinSensors{}, *s);
                });
            });
            proxy->CabinSensors.Subscribe(10);
        }
        else if constexpr (has_on_direct_event_v<Derived, vehicle_data::CabinSensorData>) {
            proxy->CabinSensors.SetReceiveHandler([this, proxy]() {
                proxy->CabinSensors.GetNewSamples([this](auto&& s) {
                    self().on(*s);
                });
            });
            proxy->CabinSensors.Subscribe(10);
        }
        // Event: VehicleSpeed (vehicle_data::SpeedData)
        if constexpr (has_on_event_v<Derived, powertrain::events::VehicleSpeed, vehicle_data::SpeedData>) {
            proxy->VehicleSpeed.SetReceiveHandler([this, proxy]() {
                proxy->VehicleSpeed.GetNewSamples([this](auto&& s) {
                    self().on(powertrain::events::VehicleSpeed{}, *s);
                });
            });
            proxy->VehicleSpeed.Subscribe(10);
        }
        else if constexpr (has_on_direct_event_v<Derived, vehicle_data::SpeedData>) {
            proxy->VehicleSpeed.SetReceiveHandler([this, proxy]() {
                proxy->VehicleSpeed.GetNewSamples([this](auto&& s) {
                    self().on(*s);
                });
            });
            proxy->VehicleSpeed.Subscribe(10);
        }
    }

    void bind_powertrain_fields(powertrain::proxy::PowertrainProxy* proxy) {
        if (!proxy) return;
    }
};

// Convenience alias mapping Component name to Executable Actor
template <typename Derived, reaktar::StrictValidation Validation = reaktar::StrictValidation::kEnabled>
using VehicleSupervisorAppActor = VehicleSupervisorActor<Derived, Validation>;
using VehicleSupervisorAppActorBase = VehicleSupervisorActorBase;

} // namespace generated
} // namespace reaktar