// ==============================================================================
// Reaktar - Reactive Actor Framework for AUTOSAR Adaptive
// Part of the Pyarx project: https://github.com/pyarxlab/reaktar
//
// Generated AUTOSAR Adaptive Tag Definitions
// DO NOT EDIT DIRECTLY - GENERATED BY reaktar scripts/generate_actor.py
// ==============================================================================

#pragma once

namespace reaktar {
namespace tags {

namespace body_control {
namespace methods {
    struct FlashLights {};
    struct LockDoors {};
} // namespace methods
namespace fields {
    struct OutsideAirQuality {};
    struct RainSensorLevel {};
    struct TargetCabinTemperature {};
    struct WindowPosition {};
} // namespace fields
} // namespace body_control

namespace hmi {
namespace events {
    struct StatusNotification {};
} // namespace events
namespace methods {
    struct ShowPopup {};
} // namespace methods
} // namespace hmi

namespace infotainment::geo::navigation {
namespace events {
    struct CurrentLocation {};
} // namespace events
namespace methods {
    struct SetDestination {};
} // namespace methods
} // namespace infotainment::geo::navigation

namespace powertrain {
namespace events {
    struct CabinSensors {};
    struct VehicleSpeed {};
} // namespace events
} // namespace powertrain

namespace vehicle_supervisor {
namespace events {
    struct EmergencyAlert {};
} // namespace events
namespace methods {
    struct CalibrateOdometer {};
    struct ResetTripMeter {};
    struct SetSpeedLimiter {};
    struct TriggerDiagnostic {};
} // namespace methods
namespace fields {
    struct CalibrationKey {};
    struct CurrentDriveMode {};
    struct HardwareRevision {};
} // namespace fields
} // namespace vehicle_supervisor

} // namespace tags
} // namespace reaktar

// Convenience namespace aliases bringing generated tags into <service>::tags
namespace body_control {
    namespace tags = ::reaktar::tags::body_control;
    namespace fields = ::reaktar::tags::body_control::fields;
}
namespace hmi {
    namespace tags = ::reaktar::tags::hmi;
    namespace events = ::reaktar::tags::hmi::events;
}
namespace infotainment::geo::navigation {
    namespace tags = ::reaktar::tags::infotainment::geo::navigation;
    namespace events = ::reaktar::tags::infotainment::geo::navigation::events;
}
namespace powertrain {
    namespace tags = ::reaktar::tags::powertrain;
    namespace events = ::reaktar::tags::powertrain::events;
}
namespace vehicle_supervisor {
    namespace tags = ::reaktar::tags::vehicle_supervisor;
    namespace events = ::reaktar::tags::vehicle_supervisor::events;
    namespace fields = ::reaktar::tags::vehicle_supervisor::fields;
}
