#!/usr/bin/env python3
# ==============================================================================
# Reaktar - Reactive Actor Framework for AUTOSAR Adaptive
# Part of the Pyarx project: https://github.com/pyarxlab/reaktar
#
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Pyarx Lab
# ==============================================================================
"""
Reaktar Packager:
Packages only:
1. Standard Reaktar headers (`include/reaktar/`, `include/reaktar.hpp`)
2. Code-generated C++ headers (`include/generated_framework/`, `include/reaktar/tags.hpp`)

Nothing else (no mock_ara, no tests, no model ARXML, no demo apps).
"""

import sys
import shutil
import tarfile
import argparse
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from generate_actor import generate_code

PACKAGE_CMAKE_TEMPLATE = """# Generated by Reaktar Packager
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Pyarx Lab
cmake_minimum_required(VERSION 3.16)
project({pkg_name} LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

# Header-only interface target for Reaktar generated actor framework
add_library({pkg_name} INTERFACE)

target_include_directories({pkg_name} INTERFACE
    $<BUILD_INTERFACE:${{CMAKE_CURRENT_SOURCE_DIR}}/include>
    $<INSTALL_INTERFACE:include>
)

# Optional installation rules
include(GNUInstallDirs)
install(TARGETS {pkg_name} EXPORT {pkg_name}Targets)
install(DIRECTORY include/ DESTINATION ${{CMAKE_INSTALL_INCLUDEDIR}})
install(EXPORT {pkg_name}Targets
    FILE {pkg_name}Targets.cmake
    NAMESPACE Reaktar::
    DESTINATION ${{CMAKE_INSTALL_LIBDIR}}/cmake/{pkg_name}
)
"""

PACKAGE_README_TEMPLATE = """# {pkg_name} - Reaktar Actor Framework

Code-generated AUTOSAR Adaptive Actor and Test Bench framework for:
`{arxml_filename}`

## Directory Structure
- `include/reaktar/`: Standard Reaktar core headers (traits, static dispatcher, tag definitions).
- `include/reaktar.hpp`: Master umbrella header.
- `include/generated_framework/`: Code-generated Actor and TestBench headers for all Adaptive Applications.
- `CMakeLists.txt`: CMake package providing the `{pkg_name}` INTERFACE library target.

## Usage in CMake
Add this package to your project:
```cmake
add_subdirectory(path/to/{pkg_name})
target_link_libraries(your_application PRIVATE {pkg_name})
```
"""


def build_portable_package(arxml_path: Path, output_target: Path, pkg_name: str, create_tar: bool = True):
    print("=========================================================")
    print("  Reaktar Package Builder                                ")
    print("=========================================================")
    print(f"  Source ARXML: {arxml_path}")
    print(f"  Package Name: {pkg_name}")
    print(f"  Target:       {output_target}")
    print("---------------------------------------------------------")

    staging_dir = output_target.parent / f".tmp_{pkg_name}_staging"
    if staging_dir.exists():
        shutil.rmtree(staging_dir)
    staging_dir.mkdir(parents=True, exist_ok=True)

    try:
        inc_dir = staging_dir / "include"
        gen_dir = inc_dir / "generated_framework"
        reaktar_inc = inc_dir / "reaktar"

        gen_dir.mkdir(parents=True, exist_ok=True)
        reaktar_inc.mkdir(parents=True, exist_ok=True)

        # 1. Copy only standard Reaktar headers (excluding tags.hpp if existing, as it will be generated fresh)
        src_reaktar = PROJECT_ROOT / "include" / "reaktar"
        if src_reaktar.exists():
            for header in src_reaktar.glob("*.hpp"):
                if header.name != "tags.hpp":
                    shutil.copy2(header, reaktar_inc / header.name)
            for header in src_reaktar.glob("*.h"):
                shutil.copy2(header, reaktar_inc / header.name)

        src_reaktar_hpp = PROJECT_ROOT / "include" / "reaktar.hpp"
        if src_reaktar_hpp.exists():
            shutil.copy2(src_reaktar_hpp, inc_dir / "reaktar.hpp")

        print("  [OK] Bundled standard Reaktar headers (include/reaktar/)")

        # 2. Generate C++ Actor, TestBench, and tags.hpp from ARXML
        print(f"  ==> Generating C++ framework headers from {arxml_path.name}...")
        generate_code(arxml_path, gen_dir)

        # 3. Generate CMakeLists.txt and README.md
        cmake_content = PACKAGE_CMAKE_TEMPLATE.format(pkg_name=pkg_name)
        (staging_dir / "CMakeLists.txt").write_text(cmake_content)

        readme_content = PACKAGE_README_TEMPLATE.format(
            pkg_name=pkg_name,
            arxml_filename=arxml_path.name
        )
        (staging_dir / "README.md").write_text(readme_content)
        print("  [OK] Generated CMake configuration & README")

        # 4. Finalize output (Directory or .tar.gz archive)
        if create_tar or output_target.suffix in [".tar", ".gz", ".tgz"]:
            tar_path = output_target if output_target.suffix in [".tar", ".gz", ".tgz"] else output_target.with_suffix(".tar.gz")
            tar_path.parent.mkdir(parents=True, exist_ok=True)
            with tarfile.open(tar_path, "w:gz") as tar:
                tar.add(staging_dir, arcname=pkg_name)
            print("---------------------------------------------------------")
            print(f"  SUCCESS! Archive created: {tar_path}")
            print(f"  Size: {tar_path.stat().st_size:,} bytes")
            print("=========================================================")
            return tar_path
        else:
            if output_target.exists():
                shutil.rmtree(output_target)
            shutil.move(str(staging_dir), str(output_target))
            print("---------------------------------------------------------")
            print(f"  SUCCESS! Directory created: {output_target}")
            print("=========================================================")
            return output_target

    finally:
        if staging_dir.exists():
            shutil.rmtree(staging_dir)


def main():
    parser = argparse.ArgumentParser(
        description="Package only generated C++ sources and standard Reaktar headers."
    )
    parser.add_argument("arxml", nargs="?", default="arxml/vehicle_system.arxml",
                        help="Path to input ARXML model file [default: arxml/vehicle_system.arxml]")
    parser.add_argument(
        "-o", "--output",
        default="dist",
        help="Output destination path (directory or .tar.gz filename, default: dist/<name>.tar.gz)"
    )
    parser.add_argument(
        "--name",
        default=None,
        help="Package name (default derived from ARXML basename, e.g. vehicle_system_reaktar)"
    )
    parser.add_argument(
        "--dir-only",
        action="store_true",
        help="Output as an unpacked directory instead of a compressed tarball"
    )

    args = parser.parse_args()
    arxml_path = Path(args.arxml).resolve()
    if not arxml_path.exists():
        print(f"Error: ARXML model '{arxml_path}' does not exist.", file=sys.stderr)
        sys.exit(1)

    stem = arxml_path.stem
    pkg_name = args.name if args.name else f"{stem}_reaktar"

    out_arg = Path(args.output)
    if args.dir_only:
        out_target = out_arg if out_arg.suffix == "" else out_arg.parent / pkg_name
        create_tar = False
    else:
        if out_arg.suffix in [".gz", ".tar", ".tgz"]:
            out_target = out_arg
        else:
            out_target = out_arg / f"{pkg_name}.tar.gz"
        create_tar = True

    build_portable_package(arxml_path, out_target, pkg_name, create_tar=create_tar)


if __name__ == "__main__":
    main()
